### ISSUE TITLE
GetChatHistoryAsync delay

### ISSUE THREAD

**Issue by guyho2** [tdlib/td#1003]
I am using TDLib with .net core 3.1.
I need to call a channel history every 1 second in order to get the latest channel message every time (even if the message is the same across few seconds I want to get it every time).
Is it correct to handle it like this?:
var chatHistory = await clientApiData.ClientApi.GetChatHistoryAsync(clientApiData.ChannelPeer.Id, 0, 0, 1);

I am asking, because it seems like I am not getting the new message every time, and some messages are getting lost. Why is it?
Also, seems like this api call takes between 0-2 milliseconds, so I guess its not doing any network call, but take it locally somehow, and because of it I see that when message written to a channel I get it in 5 seconds delay from the time it written to the channel.
I need to get the message as fast as possible after it written. How can I enforce the library to always go the server and query the channel newest message?

**Comment by levlam** [comment]
This is not possible to do through TDLib. Every server request has its flood limit, so you will receive a lot of 429th errors soon and you will need to wait a lot before the request can be repeated. Instead of calling getChatHistory, you must subscribe to the channel and handle incoming `updateNewMessage` updates. The updates are sent by the server as soon as possible.

**Comment by guyho2** [comment]
Thanks!
