### ISSUE TITLE
Problem on debug WebAssembly

### ISSUE THREAD

**Issue by masoudit** [tdlib/td#1036]
Hi, I made change to Tdlib, but it`s worked on Tcp socket but not work correct on WebAssembly method. In fact, I don't see the problems on Browser. How can i debug and test WebAssembly edition of Tdlib with IDE ? or suggest me good methods for debugging WebAssembly ?

**Comment by levlam** [comment]
You can use logging to see what is going on. You can also try debugging the code with Chrome DevTools.

**Comment by masoudit** [comment]
Well, but my problem is that logging in code or where are the code i insert my log to show me error.
I try debugging with chrome, but don't show me, where are my problems. Maybe i have made a mistake to enable debugging on code. You can say, how to enable debugging on code or which arguments set on Emsdk to enabled debugging. (Links, tutorial and another things.)

**Comment by levlam** [comment]
You need to build TDLib with debug information by changing -DCMAKE_BUILD_TYPE=MinSizeRel to -DCMAKE_BUILD_TYPE=Debug. But debug builds will be much large and slower.

I would still prefer to log everything helpful and analyzing the logs. We don't debug WebAssembly builds separately, because they usually work out of the box.

You can find some details about debugging using Chrome DevTools in https://developers.google.com/web/updates/2019/12/webassembly. You can also try [this](https://hacks.mozilla.org/2019/09/debugging-webassembly-outside-of-the-browser/) approach.

**Comment by masoudit** [comment]
Excuse me, can you explain to me, why i have these errors:
`Session closed: [Error : 0 : Ping timeout of 5 seconds expired] 
or !Session:1:upload#0]	Session closed: [Error : 0 : Ping timeout of 135 seconds expired]`
and this error:
`WebSocket connection to 'ws:<URL>/' failed: WebSocket is closed before the connection is established.`
when should these errors be displayed?!!

**Comment by masoudit** [comment]
I found my problem, thanks!
