### ISSUE TITLE
createNewBasicGroupChat and getBasicGroup vs getChat

### ISSUE THREAD

**Issue by kanekv** [tdlib/td#1044]
I am confused how these 3 are connected.
createNewBasicGroupChat returns Chat reference (which id I guess could be used in getChat).
How getBasicGroup is used? It expected `basic_group_id` where does it come from?

**Comment by levlam** [comment]
This is described in https://core.telegram.org/tdlib/getting-started in the section https://core.telegram.org/tdlib/getting-started#tdlib-glossary.

**Comment by levlam** [comment]
As for particular questions `createNewBasicGroupChat` creates new basic group chat, but `getBasicGroup` and `getChat` returns information about existing entities by their ID.

`getBasicGroup` and `getChat` shouldn't be normally used, because all actual data is received through updates. But if they need to be used, then `basic_group_id` can be taken from `chat.type` if the chat is of type `chatTypeBasicGroup`.

**Comment by kanekv** [comment]
I have read it, just got confused why 2 different types exist. I guess that's because `basicGroup` is some kind of metadata on top of `chat`?

**Comment by levlam** [comment]
@kanekv Because there are different types of chats and basic group is one of them.
