### ISSUE TITLE
td_api::searchChatMessages returns incomplete vector of messages.

### ISSUE THREAD

**Issue by Firemoon777** [tdlib/td#11]
I tried to retrieve all messages with documents by using filter `searchMessagesFilterDocument`.
```
std::int32_t offset = 0, limit = 50;
td_api::make_object<td_api::searchChatMessages>(id_, "", 0, 0, offset, limit, std::move(filter))
```
I have response of type `object_ptr< messages >` in callback 
`response->total_count_` equals to `5` (it's correct, I checked with Telegram Desktop), but `response->messages.size()` equals to `1` and contains only newest message with document from chat. 
I tried to change limit/offset, but no luck.
How can I retrieve all messages with documents?

**Comment by levlam** [comment]
It is desired (and documented) behavior. From the parameter limit description: "Fewer messages may be returned than specified by the limit, even if the end of the message history has not been reached".
In order to get more messages, you should call again searchChatMessages with from_message_id equal to message identifier of the last received message.
Offset should be always 0, if you retrieving messages from oldest to newest.

**Comment by Firemoon777** [comment]
It was a bit confusing. I figured it out, thanks!
