### ISSUE TITLE
Before secret chat keys exchange, allow to store messages to be automatically sent after the exchange

### ISSUE THREAD

**Issue by wojpawlik** [tdlib/td#1107]
Currently one establishes a secret chat in order to write a message, but must wait for the key exchange to do so. cc @FrayxRulez

**Comment by levlam** [comment]
This is unlikely to be implemented, because this is not safe. Before you can use a secret chat, you must compare encryption keys to ensure its safety. If a message will be automatically sent when the chat is established, then it is impossible to guarantee that it will be seen only by desired recipient.
