### ISSUE TITLE
How can I know if I joined a certain chat or not?

### ISSUE THREAD

**Issue by mymike00** [tdlib/td#1121]
I'd need to know if I joined a certain public chat to display a "join" button when necessary.
I'd expect a property in the chat class that could say that, but I didn't found any.
So I thought 2 different solution:

1. look through the model of all the chats and the if the chat I'm handling is present or not
2. call `getChatMember` with my id and the id of the chat: if it returns an error it means I'm not in the chat and thus I'll show the "join" button

What's the recommended  way to do that?

**Comment by levlam** [comment]
That information is always present and available, but it is stored in corresponding `basicGroup`/`supergroup` objects instead of the `chat` object. So you need to
1. Check `chat.type` field.
2.1. If it's of the type `chatTypePrivate` or `chatTypeSecret` the information is irrelevant.
2.2. If it's of the type `chatTypeBasicGroup`, take `type.basic_group_id`.
2.2.1. Get the basic group by its ID.
2.2.2. Examine `basic_group.status` field.
2.3. If it's of the type `chatTypeSupergroup`, take `type.supergroup_id`.
2.3.1. Get the supergroup by its ID.
2.3.2. Examine `supergroup.status` field.
3. Depending on the `status` you can decide whether you can join. It allows to check whether you is already a member and whether you are banned.

Between, `getChatMember` will return `chatMemberStatusLeft` for accessible non-joined chats.

**Comment by mymike00** [comment]
Ah, I didn't think about that. Thank you!
