### ISSUE TITLE
Confused about auth code

### ISSUE THREAD

**Issue by quetzalsly** [tdlib/td#1129]
I recently got td working with node through tdl, it asks me for phone number and then auth code.

I entered the phone number and it passed but then the auth code said something about SMS, I checked my phone for 5 minutes no such thing. Turns out I had to run the normal telegram desktop app during the state where my node app was between connect() and login().

Is this normal behavior? can I run the desktop app and my node app same time? do I have to do this auth code often? like for example on relaunching my node app or disconnects?

Also a bit confused on bots vs users, lets say I am a user member of 5 channels. I want to monitor those channels in my node app for new messages and simply log them. I want to run this on a server with minimal human interactions for example, should I be using bots or user mode? I am not sure if bots can even join channels?

**Comment by levlam** [comment]
You can do through TDLib exactly the same that you can do through any other Telegram client. You don't need to have access to other logged in devices to be able to log in or log in again after every restart.

In `authorizationStateWaitCode` you receive `authenticationCodeInfo` with exact information about the way the code was sent. Usually the code is sent to another recently active client first, in which case `code_info.type` is of type `authenticationCodeTypeTelegramMessage`. The field `code_info.next_type` contains information about the next method, which will be used for code delivery. It is usually of the type `authenticationCodeTypeSms`.

Bots can be added to channels only by their administrators. If you are an administrator of the channels, then you can use a bot, but it would be simpler to control the bot through the Telegram Bot API. Otherwise you can join them only as a user and need to handle `updateNewMessage` updates from the channels.

**Comment by quetzalsly** [comment]
Thanks for the explanation! I just wanted to ask one more thing without opening a new issue. These are the updates I need to handle for my task I think?

```
updateNewMessage //New message comes even when not having a channel selected?
updateMessageContent //Do I need to handle this in the rare case when a channel admin edits the message?
updateFile //Do I need to handle this as well? or do I simply parse photo info from updateNewMessage?
```

**Comment by levlam** [comment]
Handling of `updateNewMessage` and` `updateMessageEdited` + `getMessage` should be enough for your needs.

**Comment by quetzalsly** [comment]
Fantastic thanks :)
