### ISSUE TITLE
[Questions] How to correctly work with authorization state in Java/Android?

### ISSUE THREAD

**Issue by sapelkinAV** [tdlib/td#123]
1. Is there any way to manage authorization state from tdlib client(without using asynchronous UpdateHandler)?
2. How to correctly log out from tdlib? I tried adopt java example to my android app, but even after I called
`client.send(TdApi.Close(), defaultHandler)`
on the next startup I was still authorized.

**Comment by FrayxRulez** [comment]
> How to correctly log out from tdlib?
`TdApi.LogOut`

**Comment by levlam** [comment]
1. [Java example](https://github.com/tdlib/td/blob/master/example/java/org/drinkless/tdlib/example/Example.java) contains comprehensive implementation of managing AuthorizationState. You must use UpdateAuthorizationState for that, because there are a lot of tricky authorization states which can't be handled in the other way.
2. To log out you need to use TdApi.LogOut.

**Comment by isopen** [comment]
A simple example can be found here [vanish](https://github.com/isopen/java/tree/master/Vanilla/app/src/main/java/com/isopen/vanilla)

**Comment by isopen** [comment]
Send pull request in "vanish rep" (after you finish the application). Thanks.

**Comment by sapelkinAV** [comment]
it was helpful. Thanks.

**Comment by rishabh-gupta-boop** [comment]
very helpfull thankyou soo much
