### ISSUE TITLE
Cross compilation with ENABLE_JNI is impossible

### ISSUE THREAD

**Issue by Cavallium** [tdlib/td#1233]
The CMakeLists.txt in `td/generate` makes impossible to build tdjni because it copies JavadocTlDocumentationGenerator only if the target is "install".

To cross compile, the target would be "prepare_cross_compiling", not "install", so the following lines don't work:
```CMake
  if (TD_ENABLE_JNI)
    install(TARGETS td_generate_java_api RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}")
    install(FILES JavadocTlDocumentationGenerator.php TlDocumentationGenerator.php DESTINATION "${CMAKE_INSTALL_BINDIR}/td/generate")
    install(FILES scheme/td_api.tlo scheme/td_api.tl DESTINATION "${CMAKE_INSTALL_BINDIR}/td/generate/scheme")
  endif()
```
I fixed it temporarily by replacing that lines with this:
```CMake
  if (TD_ENABLE_JNI)
    install(TARGETS td_generate_java_api RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}")
    file(COPY JavadocTlDocumentationGenerator.php TlDocumentationGenerator.php DESTINATION "${CMAKE_INSTALL_BINDIR}/td/generate")
    file(COPY scheme/td_api.tlo scheme/td_api.tl DESTINATION "${CMAKE_INSTALL_BINDIR}/td/generate/scheme")
  endif()
```

I'm currently building so I don't know if there are other bugs with cross compilation with jni enabled.

**Comment by levlam** [comment]
Of course, crosscompilation with TD_ENABLE_JNI is possible, otherwise we wouldn't be able to build TDLib for Android.

You don't need to copy `JavadocTlDocumentationGenerator.php` and other files anywhere, unless you install TDLib. You can just use them from their original location.

The target `td_generate_java_api` is not built at all if TDLib is crosscompiled, For JNI interface cross-compialtion, you need to run natively both
```
cmake --build . --target prepare_cross_compiling
cmake --build . --target td_generate_java_api
```
prior the cross-compilation.
