### ISSUE TITLE
How to retrieve chat participants via TDLib

### ISSUE THREAD

**Issue by ashvydkyi** [tdlib/td#1234]
hey guys

Can you please tell me, how to retrieve the list of participants for **Basic Groups** and **Super Groups** and **Private Chat**?
When a message update received - only a chat_id is present.
When chat information received - no participants there.

Thank you in advance.

**Comment by levlam** [comment]
That's because groups in Telegram can have up to 200000 members and channels can have unlimited number of members. It is impossible to return all of them in every update or even in information about the chat.

Private chats can have at most 2 members. The other member is stored in the object `chatTypePrivate`.
Basic group members can be received through the method `getBasicGroupFullInfo`.
Supergroup members can be received through the method `getSupergroupMembers`.

**Comment by ashvydkyi** [comment]
@levlam thx!

**Comment by ashvydkyi** [comment]
@levlam is it possible to get `GetBasicGroupFullInfo` before retrieving `UpdateNewMessage`?

**Comment by levlam** [comment]
How are they connected?

**Comment by ashvydkyi** [comment]
@levlam I see the following sequence of updates when a new message posted to the basic group
- UpdateNewChat
- UpdateNewMessage
- UpdateBasicGroupFullInfo

Above I wasn't precise, I meant `UpdateBasicGroupFullInfo`, meaning can we retrieve `UpdateBasicGroupFullInfo` before 
`UpdateNewMessage`?

**Comment by levlam** [comment]
All the updates are independent. You receive an update, when it is needed. You definitely can receive `updateBasicGroupFullInfo` regardless of receiving any other mentioned update.
