### ISSUE TITLE
downloadFile not working in new JSON API

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [tdlib/td#1255]
Hi, i'm trying out the new JSON API, Please confirm if we need to include `@client_id` in  `downloadFile  `requests.

{"@client_id": 1, "@extra": "001", "@type": "downloadFile", file_id: 1036, limit: 0, offset: 0, priority: 1, synchronous: true}

**Comment by CharlesOkwuagwu** [comment]
Seems to work, with or without `@client_id`

**Comment by levlam** [comment]
Currently, you don't need to include @client_id in requests. The client ID is specified separately as td_send parameter.

**Comment by CharlesOkwuagwu** [comment]
@levlam Noted. 

Please also, is there any direct benefit of the new API?

**Comment by levlam** [comment]
It allows to use one receiver thread regardless of the number of simultaneously used TDLib instances. This is supposed to solve at least Node.JS issues with node-ffi module, which doesn't properly support multithreading environment. It should also help if you need to use 10000+ instances simultaneously.

Also new API is safer, because it doesn't involve passing raw pointers to the methods, and simpler, because instance lifetime is managed automatically, so there are less functions with less parameters.
