### ISSUE TITLE
WebAssembly build instructions

### ISSUE THREAD

**Issue by JoseExposito** [tdlib/td#127]
The README.md file indicates that TDLib is compatible with WebAssembly, however, I was not able to find instructions of how to build it. 

Any advice to build a WebAssembly version of the library?

**Comment by isopen** [comment]
Oh, oh, oh, hard. Currently we have not built using Emcripten. Try to assemble using Rust.
But let's wait for the answers of the experts on the assemblies.

**Comment by levlam** [comment]
Instructions for WebAssembly will be published later when they will be production-ready. We have verified that all basic TDLib functionality works in browsers when it is compiled to WebAssembly, but we can't publish our WebAssembly examples now because of existing technical limitations. We will likely mitigate them in 1-2 months and publish build instructions for WebAssembly and/or TDLib npm package.

**Comment by isopen** [comment]
WebAssembly is still under development. The technology is relatively fresh. If this technology is completed, then javascript can smoke.

**Comment by restYura** [comment]
@isopen I managed. It is necessary simply to understand modern technologies.

**Comment by iansowinski** [comment]
@levlam can you share how situation with WASM looks like at this point?

**Comment by levlam** [comment]
@iansowinski Situation is pretty the same. Currently, to use TDLib in a browser, additional Websocket to TCP proxies are needed. They IPs need to be hard coded to TDLib source code, which is acceptable only for testing purposes. When we resolve this issue, we publish detailed build instructions along with supporting TDLib npm package.

**Comment by UnblockerUsername** [comment]
eg: https://github.com/tdlib/td/issues/18

**Comment by isopen** [comment]
eg: https://github.com/isopen/twasm

**Comment by halkliff** [comment]
So, how is the status upon support on WebAssembly?

**Comment by halkliff** [comment]
@levlam So, how is the status upon support on WebAssembly? I've got a new Telegram client project, and I wanted it to be also available on the web using TDLib.

**Comment by MattNguyen** [comment]
@levlam is there any update on this? Also looking to get started on a Telegram client project soon!

**Comment by Niek** [comment]
TDLib hasn't been updated in over 7 months... Webogram (Telegram for web) not in 5 months. Is it dead or closed source now?

**Comment by levlam** [comment]
@MattNguyen Since 1.3.0 there was a lot of improvements in interaction of TDLib with browser's API. TDLib has been successfully used to create a web client for Telegram with all of benefits provided by TDLib: https://evgeny-nadymov.github.io/telegram-react / https://github.com/evgeny-nadymov/telegram-react. The underluying JS library tdweb will be made public along with TDLib 1.4.0 release. Source code and build instructions for tdweb was already added as an example of TDLib usage in a browser to TDLib development version. The only part there, that we need to improve before release, is tdweb's documentation and usage instructions.

TDLib 1.4.0 is expected to be released after Telegram X stable release and Bot API 4.2.0 release.

**Comment by levlam** [comment]
@Niek TDLib source code will be updated soon, likely this month.

I can tell nothing about Webogram future, but API scheme on the site will not be updated. You can find the actual scheme in a published source code of any Telegram client, but writing a good Telegram client using these methods is a really hard task. Having the actual scheme doesn't help at all to achieve that. Instead, TDLib provides a simple to use and fully-documented API for interaction with Telegram servers, which makes the interaction very simple.

**Comment by Niek** [comment]
@levlam good to hear you're preparing to release the updated source of TDlib (I assume this includes the "TDweb" source that is unavailable right now). The telegram-react project looks promising, in my tests I've been able to reach much higher downloads speeds compared to Webogram.

If you're not going to update the scheme on the site, maybe change it to link to something like https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/scheme.tl

**Comment by isopen** [comment]
Maybe https://github.com/tdlib/td/issues/508 helps understand that tdlib works fine in browsers (long ago). It remains the case for small. Design the architecture of the screens and adjust their switching.

**Comment by tjhorner** [comment]
@Niek I have a docs site with the latest layer: https://schema.horner.tj

Open source, too: https://github.com/tjhorner/schema.tl

**Comment by Niek** [comment]
@tjhorner that's amazing, thanks for linking it in here

**Comment by levlam** [comment]
TDLib 1.4.0 includes an [example](https://github.com/tdlib/td/tree/master/example/web) of TDLib usage in a browser. You can also use NPM package [tdweb](https://www.npmjs.com/package/tdweb) if you don't want to build TDLib yourself.
