### ISSUE TITLE
Multiple pinned messages API

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1275]
TDLib 1.6.10 has multiple pinned messages feature.  API resembles scheduled messages, but instead of `getChatScheduledMessages` there is search filter `searchMessagesFilterPinned` and additional `getChatPinnedMessage` method.  This is a bit inconvenient, because to get know that chat has any pinned message it requires client to make additional request to the TDLib.  For scheduled messages `chat` has `has_scheduled_messages` property.

Maybe add `newest_pinned_message_id` property (or maybe even keep old `pinned_message_id`!) to the chat instead of `getChatPinnedMessage` method, what do you think?

Thanks

**Comment by levlam** [comment]
The pinned message API is made according to what the client shows in the interface. The shown pinned message depends on the current position in the chat. Clients need to search for the next pinned message from the current position to show the message. Given the chats are usually opened from the first unread message or from the previous position, knowing the newest pinned message is useless for them in most cases.

The other difference from scheduled messages is that a chat can have at most 100 scheduled messages and unlimited number of pinned messages, so the requests like `getChatScheduledMessages` are impossible.

The `pinned_message_id` field was removed because there is no way to keep it up-to-date whenever the newest pinned message is deleted, or a message gap in a supergroup is encountered. There was an attempt to keep `pinned_message_id` and add additional `is_pinned_message_id_known` flag, but this was confusing and almost unusable.

**Comment by zevlg** [comment]
Thanks, this makes sense!

**Comment by zersiax** [comment]
I'm curious, is it not possible to get a list of the current chat's pinned messages at all, then? I know of a client or two who's managing this and was looking into the possibilities for retrieving this information, but only the newest pinned message appears accessible unless I'm missing something?

**Comment by levlam** [comment]
@zersiax Pinned messages can be received using the method `searchChatMessages` with the filter `searchMessagesFilterPinned`.
