### ISSUE TITLE
Must have filter counters api

### ISSUE THREAD

**Issue by a-x-** [tdlib/td#1309]
Currently all clients implement this performance critical must have feature themselves.
And some clients haven't filters (folders) badge counters

**Comment by a-x-** [comment]
What I means:
![](https://user-images.githubusercontent.com/6201068/98350125-f6ba0200-202b-11eb-9204-c23400068e39.png)

**Comment by a-x-** [comment]
<img width="928" alt="Screenshot 2020-11-25 at 11 18 39" src="https://user-images.githubusercontent.com/6201068/100200693-05e7ed80-2f10-11eb-9db4-8f33e8004f4d.png">

**Comment by a-x-** [comment]
Looks like it's really hard: https://github.com/TelegramMessenger/Telegram-iOS/blob/7fb0b48ded4b83297453444c9aba89139c4a726a/submodules/ChatListUI/Sources/ChatListFilterPresetListController.swift#L329-L425

**Comment by levlam** [comment]
TDLib has this and other unread message/chat counters implemented when a message database is used. In telegram-react message database is disabled because of browser restrictions to improve launch time. If message database is not used, the only way is to implement the counters is to load all the chats from the server and manually count the number of unread messages/chats. This is supposed to be done client-side now.

**Comment by a-x-** [comment]
All chats loading is preffered way over enabling message db, am I right? Is it be more performant?

Oh, okay, I’ll try to implement it, looks like it will significantly downgrade its perf
