### ISSUE TITLE
Doubled value for "reply_count" in messageReplyInfo

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1327]
In an ordinary supergroup chat, if I execute "getMessage" method directly I got "reply_count" doubled of actual value.

```
getMessage chat_id=-100xxx message_id=366371405824
==>
{"@type": "message", "id": 366371405824, ... "interaction_info": { .. "reply_info": { .. "reply_count": 8 ..}}}
```
However If I do:
```
getMessageThread chat_id=-100xxx message_id=366371405824
==>
{... messages:[{"@type": "message", "id": 366371405824, ... "interaction_info": { .. "reply_info": { .. "reply_count": 4 ..}}}]}
```

After `getMessageThread` execution `getMessage` also starts to return correct value for "reply_count".

Is this a bug or a feature?

Thanks

**Comment by zevlg** [comment]
I see this behaviour only in *some* supegroups.  In most supergroups "reply_count" value is correct out of box, without need for `getMessageThread` call

**Comment by levlam** [comment]
This happens when a lot of old messages are received. Server returns *current*, up-to-date value of reply_count and TDLib increments it again when receiving new replies to the message. It is not possible to fix this reliably without changes of the server API, but for the most cases it has already been fixed in the private TDLib version and will work better in TDLib 1.7.1.

**Comment by levlam** [comment]
Should be fixed in master.
