### ISSUE TITLE
GetChats only works once

### ISSUE THREAD

**Issue by miraclefoxx** [tdlib/td#1369]
I'm trying to make sense of the tdlib and Telegram API overall.
First obvious thing after authentication would be to get the list of chats.

So I'm calling GetChats with the following parameters: (TdApi.ChatListMain, Long.MAX_VALUE, 0, 5)
Getting back a few chats, seeing IDs, all good.
That is, until I restart my app and try to do the very same thing once more. 
Same call returns zero chats, until I delete tdlib db and start fresh. 

What's happening here?

I figured one has to maintain cache with all chats/users and such manually, as these are not stored in tdlib db.
But what happens, if I corrupt my cache somehow? 
Shouldn't there be a way to start fresh without re-authentification?

As a sidenote, what exactly _is_ GetChats returning? It's obviously not a list of all chats. Are these chats I didn't receive updates for yet?

**Comment by jumoog** [comment]
i think thats related to #751

**Comment by miraclefoxx** [comment]
Thanks @jumoog, it indeed is.
It's somewhat reassuring to know I'm not the only one who struggles to conceptualize api behaviour, but doesn't answer the questions.
I wrote a rather lengthy intro, so will try to boil it down:
1. What's the strategy to reconciliate of inconsistent\corrupted application cache against Telegram servers?
2. What's GetChats returning, if not all the chats?

**Comment by levlam** [comment]
1. Cache can't be corrupted or inconsistent, unless there is a bug in app's code. App should maintain only in-memory cache of some data, so any such bug if fixed by app restart.
2. GetChats returns identifiers of some consecutive chats from the list, but they can be ignored, because all information about the chats has already been received through updates.

Chat list receiving is described in https://core.telegram.org/tdlib/getting-started#getting-the-lists-of-chats, including a Java example, but you may need to read the whole https://core.telegram.org/tdlib/getting-started to understand some concepts.

**Comment by miraclefoxx** [comment]
Thanks, @levlam. Your explanation clears it up a little, but there's still pieces of a puzzle I'm missing.
If app maintains only in-memory cache, how do I populate it on app restart? 

Focusing on the subject issue, let's use getting all chats as an example.
Even the sample apps (looking at java) aren't clearing this up for me...

Say, I restart my app. Since newChat updates were already ingested in previous run, in-memory caches won't be populated.
How does one request same data again? Are tdlib db files supposed to be deleted before new app run?

**Comment by levlam** [comment]
Nothing is supposed to be deleted.

The data is sent on request. If app needs more chats, it call getChats and receive information about the chats through updateNewChat and other updates.

**Comment by Flohack74** [comment]
Okay let me chime in here, I have the opposite problem on tdlib 1.6:
- We had decided in the beginning that for our app its easier to request all chats on startup, instead of doing this during scrolling of the list
- Code was added for tdlib 1.4 to request 25 chats initially (getChats with the usual parameters). Then, when chats were received, it would request all that chats, and after a brief delay, continue with getChats and the right offset params
- Now for optimization I look into doing it really asynchronously. But I found out, even if requesting only 10 chats, tdlib 1.6 now sends me all chats through updates. Confused ;)
- Can I kick out the whole getChats workflow now, is it guaranteed that tdlib will update all chats?

**Comment by Flohack74** [comment]
Lowered the number of chats to 10. Its even more interesting, during processing of getChats, other updates are incoming, so even the initial getChats does effectively do nothing:
```
qml: Chat ListView loaded, requesting chats...
Received 10 chats
Chat -334781720 already received, ignoring
Chat 156359641 already received, ignoring
Chat 112649785 already received, ignoring
Chat -209613759 already received, ignoring
Chat -230093272 already received, ignoring
```
The other 5 chat Ids in chats message were 0, so they are filtered out here already. Thats also a bit strange, if I request the list initially with the 2^64-1 offset, shouldn´t I receive 10 valid IDs?

**Comment by levlam** [comment]
@Flohack74 

> is it guaranteed that tdlib will update all chats?

No. TDLib never sends more than 1 server request for getting chat list implicitly, so you will not receive all chats if there are more than 200 of them.

Currently, TDLib slowly, with explicit delays preloads the whole Main/Archive chat list from database after first getChats request to provide efficient loading of filter chat lists. If you want chat list to be loaded as fast as possible, you need to send getChats requests explicitly.

> the initial getChats does effectively do nothing

getChats triggers chat list loading. Chats and their position are received through updates, so if updates are handled correctly, getChats response can be safely ignored.

> if I request the list initially with the 2^64-1 offset, shouldn´t I receive 10 valid IDs?

getChats can never return invalid chat_id in the response.

**Comment by CaliforniaMountainSnake** [comment]
@levlam Hello, I also have problems with the main chat list.
I use Java example and, as I understand, `mainChatList` should **ALWAYS** be actual because all information about main chat list positions is handled by the example code via updates.

But when I join a new chat, `mainChatList` doesn't change. How is this possible?

**Comment by levlam** [comment]
`mainChatList` in the example is always actual and contains all chats in the loaded part of the main chat list.

**Comment by CaliforniaMountainSnake** [comment]
> the loaded part of the main chat list.

What do you mean? What is the `loaded part`?

**Comment by levlam** [comment]
`order` is known only for the chats in the some prefix of the chat list. Otherwise, clients wouldn't be able to detect existence of missing chats in the chat list.

**Comment by CaliforniaMountainSnake** [comment]
> some prefix of the chat list

@levlam Please, tell us more detail, what are the "parts" and "prefixes" of the chat list? How to get a **full** chat list?

If I call `GetChats` multiple times until it returns an empty chat IDs array, may I be sure I got a full and actual chat list?

**Comment by levlam** [comment]
> If I call GetChats multiple times until it returns an empty chat IDs array, may I be sure I got a full and actual chat list?

If you correctly adjust `offset_order` and `offset_chat_id`, then yes.
