### ISSUE TITLE
Two messages received in a supergroup while offline – no updateNewMessage after login

### ISSUE THREAD

**Issue by ars3niy** [tdlib/td#1370]
Got another instance of missing updateNewMessage. Again in a supergroup, but this time only two message arrived while offline, there's no null updateChatLastMessage and no updateNewMessage for the char at all.

How to display incoming messages in this case?

**Comment by ars3niy** [comment]
The guy who sent me the log didn't want me to share it further in its entirety but I've sent some relevant parts to the bot.

**Comment by levlam** [comment]
There was only two new messages in the supergroup since last launch.

There was no `updateNewMessage` updates, because you seems not to use message database, so state of chat objects is not persistent between client restarts. The newest chat message was received in response to `getChats` request and it was used to initialize chat's state and set as a last chat message. After that `updateNewMessage` will be sent only about messages newer than current last chat mssage.

**Comment by ars3niy** [comment]
Message database was indeed disabled, I'll enable it and see how it goes.
