### ISSUE TITLE
Problem with the getChatHistory function in some groups

### ISSUE THREAD

**Issue by BarnameESF** [tdlib/td#1380]
Hi
Do not be tired
We are using tdbot 1.7.0. We use the getChatHistory function to capture group messages, and then delete group chats with the deleteChatMessagesFromUser function. In some groups we got into trouble. After the account clears the chats of a group for several hours with this method, the getChatHistory function returns zero messages even after one minute of repetition, and finally our operation has problems.
No errors are recorded in the log file and the two functions do not display any errors.
Thanks for the help.

**Comment by levlam** [comment]
Send TDLib log to @tdlib_bot in Telegram.

**Comment by BarnameESF** [comment]
I sent you two examples from two groups with two different accounts

**Comment by levlam** [comment]
This happens because you are deleting messages, which are about to return in `getChatHistory`. TDLib has protection from returning already deleted messages, even the server returned them, so server response is useless for answering `getChatHistory` request. To mitigate the issue you should not send simultaneous `getChatHistory` and `deleteChatMessagesFromUser` requests. Sending a `getChatHistory` request only after all `deleteChatMessagesFromUser` requests complete will also help you to avoid exceeding rate limits.

**Comment by BarnameESF** [comment]
I even programmed it the way you said, and after the message is deleted, it goes to the next cleanup request, but still the getChatHistory function returns zero messages.

**Comment by levlam** [comment]
@BarnameESF Could you update to the latest TDLib version and send me again TDLib's log?

**Comment by BarnameESF** [comment]
That means I use tdlib 1.7.1 directly?

**Comment by levlam** [comment]
Yes, with TDLib 1.7.1.

**Comment by serbadima** [comment]
-

**Comment by serbadima** [comment]
ребята одолжите 6000₽ @ +79031579669 сбербанк выгоняют из квартиры
