### ISSUE TITLE
Build without Visual Studio on Windows

### ISSUE THREAD

**Issue by dancojocaru2000** [tdlib/td#1429]
Is there a way to build without Visual Studio on Windows (perhaps using MinGW)?

**Comment by levlam** [comment]
Yes, you can build TDLib using MinGW in the same way as any other project using CMake. But this could be harder and requires some experience in С++ code building.

**Comment by dancojocaru2000** [comment]
While I do have experience aith building C++ code, I don't have experience with CMake, and I couldn't quite find how to get CMake to use a different compiler.

**Comment by levlam** [comment]
CMake will automatically choose correct compiler if you run it in the correct MinGW environment.

**Comment by dancojocaru2000** [comment]
It still attempts to use Visual Studio despite also having g++ available. Is there a way to force the choice?

**Comment by levlam** [comment]
You need to run cmake from the correct environment, i.e. "MSYS2 MSYS", and not from "MSYS2 MinGW X-bit".

**Comment by dancojocaru2000** [comment]
Do I have to? It seems odd that I'd have to do that.

Ideally, I would like cmake to just use the environment in `C:\Mingw\`, with the C++ compiler `C:\Mingw\bin\g++.exe`, without having to run it from "MSYS2 MSYS".

**Comment by levlam** [comment]
These console sets up a fully correct environment. Using it is the simplest way.

Otherwise you need to write a CMake toolchain file for MinGW, or manually specify path to a really a lot of tools. See https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/cross_compiling/Mingw for the example of the former approach on Linux. See build instructions in https://tdlib.github.io/td/build.html?language=C%2B%2B for Ubuntu 20, with LTO and clang enabled for an example of the latter approach.
