### ISSUE TITLE
get file URL

### ISSUE THREAD

**Issue by MoroZvlg** [tdlib/td#145]
Is it possible to get URL of RemoteFile? getRemoteFile receive file object that doesn't contain file_path. But in API docs says: "Can be used to register a URL". What I'm missing? How can i "register URL"?

**Comment by seiya-git** [comment]
Use downloadFile after using getRemoteFile.

**Comment by MoroZvlg** [comment]
One more question. Is it possible to get all chats, without their id. Or where i can take all chats's id...?

**Comment by levlam** [comment]
Is getChats a method, which you need?

**Comment by MoroZvlg** [comment]
In this case I need chat's IDs.

**Comment by seiya-git** [comment]
Last 100 chats:
```javascript
{
    '@type': 'getChats',
    'offset_order': '9223372036854775807',
    'offset_chat_id': 0,
    'limit': 100,
}
```

**Comment by MoroZvlg** [comment]
My bad. Didn't read docs well enough. Thanks for help! and sorry for stupid questions)

**Comment by erfannf** [comment]
Hey guys. I'm using TDLib in Node.JS via FFI. I'm confused downloading photos. getRemoteFile accepts STRING file id and calling it returns the file itself: 
 `
{'@type': 'getRemoteFile',
  'remote_file_id': 'AgADBAADj6sxG1DZ4FNqhx2hDKpy6XRPkRoABFiyRSjl7chZn0wCAAEC'}
 `

RESULT of getRemoteFile:
`
{ '@type': 'file',
  id: 1,
  size: 0,
  expected_size: 0,
  local:
   { '@type': 'localFile',
     path: '',
     can_be_downloaded: true,
     can_be_deleted: false,
     is_downloading_active: false,
     is_downloading_completed: false,
     downloaded_prefix_size: 0,
     downloaded_size: 0 },
  remote:
   { '@type': 'remoteFile',
     id: 'AgADBAADj6sxG1DZ4FNqhx2hDKpy6XRPkRoABFiyRSjl7chZn0wXXXX',
     is_uploading_active: false,
     is_uploading_completed: true,
     uploaded_size: 0 } }
`


The problem is downloadRemoteFile does not respond to query as it requires NUMBER file_id as one its arguments. Which NUMBER parameter should be passed to it?

Would you please help? Thanks

**Comment by levlam** [comment]
After you have received File object through getRemoteFile, you can pass its id to downloadFile method, "id: 1" in your example.
