### ISSUE TITLE
Workaround for Error: Receive is called after Client destroy

### ISSUE THREAD

**Issue by comerc** [tdlib/td#1455]
Hack of tdlib.go for DestroyInstance()

```go
var IsClosed = false

func NewClient(config Config) *Client {
  // ...
  go func() {
    for !IsClosed {
      // get update
      updateBytes := client.Receive(10)
      // ...
    }
  }()
  // ...
}
```

usage:

```go
  tdlib.IsClosed = true
  time.Sleep(1 * time.Second)
  client.DestroyInstance()
```
![Снимок экрана от 2021-03-22 00-50-48](https://user-images.githubusercontent.com/1025241/111922024-c047c580-8aa8-11eb-9033-b832192deb1e.png)

https://core.telegram.org/tdlib/docs/td__json__client_8h.html

**Comment by levlam** [comment]
"Receive is called after Client destroy" is always a bug of those, who uses TDLib. You should move call to `client.DestroyInstance()` to the thread, which calls receive, instead of testing your luck with `Sleep`.

You can also use new JSON interface (`td_create_client_id`/`td_send`/`td_receive`), which removes possibility to do this bug.
