### ISSUE TITLE
Change td_json_client.h File Reference to reflect new interface

### ISSUE THREAD

**Issue by dancojocaru2000** [tdlib/td#1540]
The page for [td_json_client.h File Reference](https://core.telegram.org/tdlib/docs/td__json__client_8h.html) still describes only the old `td_json_client_*` functions.

It took me some digging through the source code to find that `td_receive` identifies the client by inserting a `@client_id` key in the response.

The documentation page (and perhaps example) should be updated to reflect the new interface as well.

**Comment by levlam** [comment]
All examples in the repository already use new interface instead of `td_json_client_*`. The new interfase is documented in the `td_json_client.h` header below the primary JSON interface for TDLib 1.X,Y, but seems to be missing from autogenerated documentation. I fixed this in the private TDLib version and combined description of both interfaces in the autogenerated documentation.

**Comment by dancojocaru2000** [comment]
I did notice after opening the issue that the interface is documented in the `td_json_client.h` header. 

However, when there is already an autogenerated documentation that is linked to, people are not really inclined to go read the source code and documentation found inside of it unless they face a problem.

Given that the present autogenerated documentation documents the old functions, people would probably prefer using them rather than try to find out how the new ones work.

As such, I think it is appropriate to close this issue once the autogenerated documentation that is found on the website is also up to date.

> and combined description of both interfaces in the autogenerated documentation.

Thank you! I look forward to seeing that live online!

**Comment by levlam** [comment]
Documentation for TDLib 1.8.0 is live now.
