### ISSUE TITLE
How to receive a limited number of chats?

### ISSUE THREAD

**Issue by sfilmak** [tdlib/td#1554]
Hello.

I am trying to build an app for watchOS based on TDLib, and I've encountered the problem with loading chats using `getChats() `(https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_chats.html). I specify the limit for messages (for example, to load 5 messages), but the app still loads all messages at once, which highly decreases the performance.

I found a similar issue on this matter (https://github.com/tdlib/td/issues/899). Is it possible at all to limit the number of received messages?

I use `getChatList()` function from this example: https://github.com/modestman/tdlib-swift/blob/master/tdlib-ios/Service/Service/ChatListService.swift

**Comment by levlam** [comment]
`getChats` returns specified number of chats. Updates about some other chats may be sent any time. This shouldn't directly affect app performance.

**Comment by sfilmak** [comment]
Hello.

Sorry, maybe I was not clear in the explanation. `getChats` returns a specified number of chats, that's right. But, inside `onUpdate` (more specifically, in `.updateNewChat` case), TDLib fetches new and new chats, in my case - all existing chats. By doing this, the performance of the app drops significantly for a certain amount of time (because the app loads all existing chats from my account, which is more than 600 conversations). 

The question is - how to prevent the library from loading new and new chats automatically? Or is it not allowed?

**Comment by levlam** [comment]
New chats are preloaded from the database by 20 chats at a time with delay 200 milliseconds between loads, which shouldn't create significant load. The preload can't be disabled, because it is needed for implementation of a lot of app features, for example, filters/folders and updateUnreadChatCount/updateUnreadMessageCount updates, If you don't need these features, you can edit TDLib's source code and disable chat preloading by returning early from the function MessagesManager::preload_folder_dialog_list.

**Comment by sfilmak** [comment]
Hello. Thank you very much for your help and the explanation.
