### ISSUE TITLE
processPushNotification example usage for iOS

### ISSUE THREAD

**Issue by keleftheriou** [tdlib/td#1599]
I’m trying to use the notifications API of TDLib as described [here](https://core.telegram.org/tdlib/notification-api).

But the payloads I’m receiving from APNS don’t seem to be suitable to pass to `processPushNotification`, since they lack required fields like `loc_key`. This is an example payload:

didReceiveRemoteNotification: [AnyHashable("from_id"): 186281, AnyHashable("msg_id"): 135, AnyHashable("aps"): {
    alert = “Some User: test";
    category = r;
    "content-available" = 1;
    sound = "0.m4a";
}]

Also the documentation for `processPushNotification` refers to "google.sent_time" and "google.notification.sound” fields.

Is this API somehow Android-specific? Am I missing something else?

**Comment by levlam** [comment]
iOS apps have a slight control over push notifications, because the notifications must be handled in a separate process with very limited resources. Because of this, TDLib's notification API is hardly suitable to deal with notifications on iOS. Currently, the notification API is supposed to be used on all OS besides iOS.
