### ISSUE TITLE
Change file download position for seeking streaming media

### ISSUE THREAD

**Issue by vkryl** [tdlib/td#161]
For now, it's not possible to implement seek for video (or any other type of media) streaming.

Probably, some function like `changeDownloadPosition(int fileId, int position, int limit)` is needed that would cancel current download requests and start download like usual from requested `int position` (and download the rest of the file, when all data from `int position` until the end of the file has been downloaded and `int limit` is not specified). `int downloadPrefixPosition, int downloadPrefixSize` in `File` would mean how many bytes available from last requested `int position` (information about other downloaded parts unlikely will be needed by clients). Any information changes would be sent via `updateFile`.

**Comment by korangu** [comment]
when will be done?

**Comment by levlam** [comment]
Support for media seeking was added in TDLib 1.4.0:
- Added the `offset` parameter to `downloadFile` which specifies the starting position
  from which the file should be downloaded.
- Added the `limit` parameter to `downloadFile` which specifies how many bytes should be downloaded starting from the `offset` position.
- Added the field `download_offset` to the class `localFile` which contains the current download offset.
- The field `downloaded_prefix_size` of the `localFile` class now contains the number of available bytes
  from the position `download_offset` instead of from the beginning of the file.
- Added the method `getFileDownloadedPrefixSize` which can be used to get the number of locally available file bytes from a given offset without actually changing the download offset.
