### ISSUE TITLE
Skipping QR code authentication

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#1645]
QR code authentication works perfectly in the TDLib 1.7.6.  I want to implement QR code auth skipping functionality, i.e. client stats with the QR code auth by default (using `requestQrCodeAuthentication` method as the reaction to `authorizationStateWaitPhoneNumber` state).  After getting login link with `authorizationStateWaitOtherDeviceConfirmation` state,  user decides that he wants to login with his phone number instead.  I've tried to call `setAuthenticationPhoneNumber`, but got the error "Call to setAuthenticationPhoneNumber unexpected".

What is the correct way to skip QR code authentication and login with the phone number when client is already in the `authorizationStateWaitOtherDeviceConfirmation` state?

Thanks!

**Comment by levlam** [comment]
Currently, there is no way to switch back to `authorizationStateWaitPhoneNumber` without logging out and creating new TDLib instance. This is required, because client in the `authorizationStateWaitOtherDeviceConfirmation` can be already logged in, but doesn't received confirmation from the server yet. To mitigate this possibility, current authorization needs to be aborted using `logOut`.
