### ISSUE TITLE
generateChatInviteLink vs createChatInviteLink

### ISSUE THREAD

**Issue by comerc** [tdlib/td#1667]
[generateChatInviteLink](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1generate_chat_invite_link.html) by tdlib has only one parameter: chat_id

but

[createChatInviteLink](https://core.telegram.org/bots/api#createchatinvitelink) by telegram-bot-api has three parameters:  chat_id, expire_date, member_limit

why? :)

**Comment by levlam** [comment]
Because `generateChatInviteLink` is used for https://core.telegram.org/bots/api#exportchatinvitelink implementation.

You can found this in no time in the Bot API source code, how other methods are implemented: https://github.com/tdlib/telegram-bot-api/blob/05b3d5fcb103d18911b5726fa57aad65d42da822/telegram-bot-api/Client.cpp#L7097.
