### ISSUE TITLE
new version tdlib 1.7.8

### ISSUE THREAD

**Issue by MetBorman** [tdlib/td#1683]
cant download next an ordered list of chats in a chat list after use function getChats().

on version 1.7.6 worked well (https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_chats.html#ad5c6852c24b3b39c48321496871a637b) after update returned the same list.

**Comment by zevlg** [comment]
Use `loadChats` since 1.7.7

**Comment by MetBorman** [comment]
w

> Use `loadChats` since 1.7.7

can you provide a link to the documentation, i cant find it

**Comment by zevlg** [comment]
> > Use `loadChats` since 1.7.7
> 
> can you provide a link to the documentation, i cant find it

//@description Returns an ordered list of chats from the beginning of a chat list. For informational purposes only. Use loadChats instead to maintain chat lists @chat_list The chat list in which to return chats @limit The maximum number of chats to be returned
getChats chat_list:ChatList limit:int32 = Chats;

**Comment by MetBorman** [comment]
> loadChats

sorry(((, i cant understand 
i have (Python):
client.sendCommand({'@type': 'getChats',
                                'chatList ': 'chatListMain',
                                'offset_order': offsetOrder,
                                'offset_chat_id': offsetChatId,
                                'limit': limit})
how to use now?
where use "loadChats"?

**Comment by levlam** [comment]
Since TDLib 1.7.7 there are two separate methods.

`getChats` was superseded by `loadChats`, which works exactly as `getChats` worked previously when `offset_order` and `offset_chat_id` were specified to be `order` and `chat_id` of the last known chat. After calling `loadChats` app will receive newly loaded chats and their position through updates.

If app doesn't want to maintain chat list in a consistent state, it can use `getChats` convenience method instead, which directly returns chat identifiers and tries to return exactly requested number of chats.

Both methods have only two parameters: `chat_list` and `limit`.

**Comment by ivk1800** [comment]
@levlam I can call ```GetChats``` multiple times for load chats again? for example case: screen with archived chats, his can be opened multiple times by user. Need load again chats of list. And for load more chats again need call ```loadChats```, but how tdlib understanding what need load more again new portion of chats, if they already loaded before? For example ```GetChats``` returned first 10 chats, ```loadChats``` loads next chats with offset 10? Old ```getChats``` with offset_order and offset_chat_id had good clarified behaviour.
