### ISSUE TITLE
Managing memory/disk space usage for tdlib

### ISSUE THREAD

**Issue by Mike497** [tdlib/td#1704]
Hi,
Could you please comment on the following questions regarding thread topic:
1. When we set 'false' to use any of databases, this means all messages will go to memory and will be never unloaded from there till application is launched? So in this case OOM error is a matter of time...
2. When we use databases, memory is much less consumed, but cached stuff goes to disk, it is also not possible to clean these databases? I tried to use optimizeStorage function, but seems it works only for e.g. downloaded files, nothing is cleared from databases. So in this case 'no space left of device' is a matter of time...
3. So without manual stopping the application we cannot do anything with above issues? Or there is any compromise possible?
Thanks in advance!

**Comment by levlam** [comment]
1. Yes.
2. Yes.
3. You can close and reopen TDLib instance programmatically from time to time. You can alsi programmatically delete `td.sqlite` database file from TDLib database directory when TDLib isn't launched. You will loose some data (mostly from secret chats) and settings, but otherwise it should have no visible impact.

**Comment by levlam** [comment]
@mib32 
1. Instances are restarted when cumulative memory usage is high on the server.
2. Bot API doesn't use SQLite databases.
3. RAM usage can be very different. Average active bot instance uses less than 1 MB RAM, but bots with constant 1000+ updates per second may need about 30 GB RAM on the first day (with much smaller RAM usage grow afterwards).

I doubt that bans are related to restarts. Moreover, there is no such thing as "ban by IP address".

**Comment by mib32** [comment]
@levlam `Moreover, there is no such thing as "ban by IP address".`
Interesting. I figured like this - after I have an event of very many restarts (let's say when my service has a crash loop and all 500 clients [not bots, mostly one country phones] restart in indefinite loop), the authorization codes stop to come (with no error logs), but as soon as a proxy is added to tdlib via method call - codes come just fine. And they stop to come for approximately 24 hours.

Ok, but that's already off-topic though.

**Comment by grittygear4937** [comment]
> 3\. You can close and reopen TDLib instance programmatically from time to time.

Hi @levlam, when you say close and reopen TDLib instance do you you mean to close TDLib client and then recreate it or we need to kill and restart the whole process with multiple clients in it?

**Comment by levlam** [comment]
You can just close the client to purge in-memory cache. The heap memory can't be returned to OS, but it will be reused by the process for new objects.

**Comment by AlexObukhoff** [comment]
I have a similar problem with memory consumption.
Having launched a 2 of json clients, I observe how the process first occupying 16mb in memory grows to more than 200mb very quickly (10-15 min). Since I plan to launch a larger number of clients (>100), this will be a big problem for me.

I tried stopping the client by calling "close" and then starting the client again. But this does not help and memory consumption continues to grow. The "destroy" call does not suit me, because it resets the client's authorization.

@grittygear4937 how do you propose to stop the client?
