### ISSUE TITLE
SponsoredMessages in console tdlib application

### ISSUE THREAD

**Issue by Mike497** [tdlib/td#1759]
Hello!
Recently I've read post from Pavel Durov (https://t.me/durov/172) about upcoming sponsored messages feature in Telegram.
Then I got notification about it in Telegram.
Also I've read some notes about required sponsored messages implementation in 3rd party apps: https://core.telegram.org/api/sponsored-messages
So, main question is - how correctly implement viewing of sponsored messages in console application?
Suppose it is not enough to call GetChatSponsoredMessages and then view them by calling ViewSponsoredMessage?

**Comment by levlam** [comment]
If you have a fully-functional console application like `tgcli`, which is able to show messages in a particular Telegram channel, then you need to show the sponsored message under the last channel message. Otherwise, if the app doesn't allow its users to access content from Telegram channels, you shouldn't do anything.
