### ISSUE TITLE
Call

### ISSUE THREAD

**Issue by yjsbutinghua** [tdlib/td#1903]
How to realize Android video call and voice call?

**Comment by levlam** [comment]
See source code of the official Android app and tgcalls library: https://github.com/DrKLO/Telegram and https://github.com/TelegramMessenger/tgcalls.

**Comment by tgtglove** [comment]
hi @levlam
seems Telegram removed support libtgvoip recently  judging by the removal of legacy code
can you confirm that now only the webrtc implementation remains working?

https://github.com/TelegramMessenger/tgcalls/commit/6250a8d541208297828c8d85111c2735525b7043

Calls do not work in Telegram x now, because it uses libtgvoip

**Comment by levlam** [comment]
@tgtglove `libtgvoip` support should have been removed some day.
