### ISSUE TITLE
How to handle ChatUnreadReactionCount properly

### ISSUE THREAD

**Issue by krelly** [tdlib/td#1923]
TDLib stops sending `updateChatUnreadReactionCount` updates if reaction is received by message that was posted a while ago, but there is a another update - `updateChatUnreadReactionCount` sent which only contains chat_id, what is the correct way to retrieve the message_id which recieved a new reaction?
The first idea that comes to mind - I can use `getChat` method and then load all messages after `last_read_outbox_message_id_` with `get_chat_history` method.

However if theres a lot of messages it would take a while, and observing how desktop client works I can see, that it already knows what message recieved a reaction, (clicking the heart button instantly takes you to that message), but i could not find any hints in documentation how this could be done.
<img width="93" alt="Screenshot 2022-04-08 at 18 52 53" src="https://user-images.githubusercontent.com/2429960/162478199-364f9a5c-d72a-4bd2-88ad-c1cdea7dbfc9.png">

**Comment by levlam** [comment]
Sorry for no response on the issue. There were known issues with chat unread reaction count, which were supposed to be fixed after TDLib update. I planned to answer the issue after the update is live, but instead the issue was lost. 

Now `updateChatUnreadReactionCount` should be always received whenever unread reaction count changes. If this doesn't happen in some case, you can send TDLib logs to https://t.me/tdlib_bot, so the issue can be fixed, 

> what is the correct way to retrieve the message_id which recieved a new reaction?

To receive messages with reactions, you need to use `searchChatMessages` with `searchMessagesFilterUnreadReaction`.
