### ISSUE TITLE
Audio calls: State machine questions

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#1945]
Hi @levlam 

I tried to sketch the following state machine for a simple call flow:

![grafik](https://user-images.githubusercontent.com/16186470/164325649-31fa43a7-a64f-4d94-8015-1b5e765fcd99.png)

However, there are some questions remaining:

- What state will follow if a user declines a call?
- Is callStateError reachable from all of the states I marked with ???
- What is the condition to transit from hanging up to discarded? 

Thanks Florian

**Comment by levlam** [comment]
> What state will follow if a user declines a call?

If the current user declines the call, then call state changes to `callStateHangingUp`, and then to `callStateDiscarded`. Otherwise state changes directly to `callStateDiscarded`.

> Is callStateError reachable from all of the states I marked with?

`callStateError` is reachable from all other states. Any call, which failed because of some (internal server) error, is in the state `callStateError`.

> What is the condition to transit from hanging up to discarded?

All successfully finished calls are in the state `callStateDscarded`, See class `CallDiscardReason` for the full list of possible reasons for call termination. Basically, `callStateDscarded` is reachable from all other states except `callStateError`.

**Comment by Flohack74** [comment]
Thx you are my hero :P
