### ISSUE TITLE
Long delay between AuthorizationStateLoggingOut and AuthorizationStateClosed

### ISSUE THREAD

**Issue by EinTheFrog** [tdlib/td#1946]
I'm testing my android client on logging in/logging out (manually) and I've noticed that there is a delay (from few seconds to few minutes) between `TdApi.AuthorizationStateLoggingOut` and `TdApi.AuthorizationStateClosed`. Is this normal behaviour? And if it is what can I do to minimize this delay (because it makes testing harder)?

P.S. I'm using _999662****_ phone numbers for logging in and set `useTestDc` to `true`.

**Comment by levlam** [comment]
This isn't intended, but there was similar report recently. Could you collect TDLib log with verbosity level 4 and send it to https://t.me/tdlib_bot?

**Comment by levlam** [comment]
Ah. I missed that you are logging out and not just closing instance. Then some delay is expected, because a lot of things must be done locally and on Telegram servers. But in your case the long delay was caused by usage of the test account, which can do a very limited number of server-side requests.

**Comment by EinTheFrog** [comment]
Didn't know about this limitation. Thank your for your answer.
