### ISSUE TITLE
Ubuntu packages outdated & will not install

### ISSUE THREAD

**Issue by lproven** [tdlib/td#2036]
I tried to install the packages from `https://download.opensuse.org/repositories/home:/ars3n1y/xUbuntu_21.10/` on the current Ubuntu (which is also an LTS release of course).

It fails with:

    The following packages have unmet dependencies.
     libpurple-telegram-tdlib : Depends: libssl1.1 (>= 1.1.1) but it is not installable
                            Depends: libwebp6 (>= 0.5.1) but it is not installable

Building from source also fails:

````
CMake Error at CMakeLists.txt:7 (find_package):
  By not providing "FindTd.cmake" in CMAKE_MODULE_PATH this project has asked
  CMake to find a package configuration file provided by "Td", but CMake did
  not find one.

  Could not find a package configuration file provided by "Td" with any of
  the following names:

    TdConfig.cmake
    td-config.cmake

  Add the installation prefix of "Td" to CMAKE_PREFIX_PATH or set "Td_DIR" to
  a directory containing one of the above files.  If "Td" provides a separate
  development package or SDK, be sure it has been installed.
````

I rarely build anything from source and haven't since the 1990s, TBH. I have no idea how to troubleshoot this.

Could we please have some updated binary packages?

**Comment by levlam** [comment]
Your question will be more suitable for https://github.com/ars3niy/tdlib-purple repository, which uses TDLib, but is maintained by an independent developer.

Regarding the second error, you need to have TDLib installed in order to build tdlib-purple. You can find build instructions for TDLib at https://tdlib.github.io/td/build.html. If you install it to /usr/local, it should be automatically found by tdlib-purple.
