### ISSUE TITLE
tdlib wouldn't auto delete files in temp folder 

### ISSUE THREAD

**Issue by darkaforest** [tdlib/td#2154]
I'm using tdlib with Java to download files like videos and photos, and it worked well, when a file has been completed **I copy it to my own folder and immediately delete it in the original folder** that `TdApi.UpdateFile` returns in `updateFile.file.local.path`.

My issue is that when it is all done, there are still lots of files in the tdlib's temp folder. They are named like... auto increasing number that just like local file id in tdlib. I've set `enableStorageOptimizer` to true, but it seems like those temp files haven't been auto deleted at all.

Am I doing anything wrong?

**Comment by darkaforest** [comment]
I've just noticed that the files in the temp folder, their's number is much smaller than my current downloading file. Let's say if the files in the temp folder are 755, 756... then my current downloading local id is 1223, 1224...

And my program is still under development so I will force quit a lot when the file is downloading, and I don't care about the previous unfinished files, so I've just let them go. So maybe it's because tdlib is downloading those old files that I just throw away when quitting my program?  Is there any way to abort all download tasks?

**Comment by levlam** [comment]
Those are partially downloaded files. It is a bug that they aren't automatically deleted after some time by storage optimizer, which will be fixed.

If you want the files to be deleted immediately, then you need to do this manually by using `cancelDownload` and then `deleteFile` before closing TDLib instance. You can also ensure that downloading of the files is continued after app restart by using `addFileToDownloads` instead of `downloadFile`.

**Comment by darkaforest** [comment]
@levlam  thanks for your help very much!
