### ISSUE TITLE
message Id from link to tdlib message id

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#2230]
Hello,

suppose I have a link to a message like https://t.me/xyz/12345, how can I request that message from tdlib so I can open the right chat and position the view at the message? The message Ids seem incompatible...

**Comment by levlam** [comment]
All link processing is done in TDLib.

Whenever a link is clicked by the user, app needs to do the following:
1. Call `getInternalLinkType`.
1.1. If the method succeeds, process returned `internalLinkType*` as documented. Done.
2. Otherwise call getExternalLinkInfo.
2.1. If received `loginUrlInfoOpen`, then just open the URL in an external browser. Done.
2.2. If received `loginUrlInfoRequestConfirmation`, then ask user's confirmation.
3. If the user rejects authorization, then just open the URL in an external browser. Done.
3.1. If the user confirms authorization, then call `getExternalLink` and opend returned URL in an external browser. Done.

For the mentioned link you will receive `internalLinkTypeMessage` on the step 1. Then "Call getMessageLinkInfo with the given URL to process the link".

**Comment by Flohack74** [comment]
Thanks for the detailed answer!

**Comment by agp22888** [comment]
Suggested method doesn't work for me. Let's say, I'm trying to get message_id for message https://t.me/telegram/288 . It's a valid message, desktop and mobile client can open it. I've tried to use `getInternalLinkType`, `getExternalLinkInfo` and `getMessageLinkInfo` with this link. Responses  were `{'@type': 'error', 'code': 404, 'message': 'Not Found', '@extra': 'my_extra', '@client_id': 1}`, `{'@type': 'loginUrlInfoOpen', 'url': '', 'skip_confirmation': False, '@extra': 'my_extra', '@client_id': 1}` and `{'@type': 'error', 'code': 400, 'message': 'URL must be non-empty', '@extra': 'my_extra', '@client_id': 1}` respectively. Is there additional requerements to use those functions?
Here's a code example:
```
tdjson_path = "./libtdjson.so.1.8.26"
tdjson = CDLL(tdjson_path)

_td_receive = tdjson.td_receive
_td_receive.restype = c_char_p
_td_receive.argtypes = [c_double]

def td_receive():
    result = _td_receive(1.0)
    if result:
        result = json.loads(result.decode('utf-8'))
    return result

link = 'https://t.me/telegram/288'
request_sent = False
while True:
    event = td_receive()
    if event:
        if not request_sent:
            print('=====SENDING CHAT INFO REQUEST=====')
            td_send({'@type': 'getInternalLinkType', 'link_': link, '@extra': my_extra})
            td_send({'@type': 'getExternalLinkInfo', 'link_': link, '@extra': my_extra})
            td_send({'@type': 'getMessageLinkInfo', 'url_': link, '@extra': my_extra})
            request_sent = True
        if (extra := event.get('@extra', None)) and extra == my_extra:
            print('======CHAT INFO RESPONSE=====')
            print(str(event))
```
