### ISSUE TITLE
getChatAdministrators returns incorrect data

### ISSUE THREAD

**Issue by kossnocorp** [tdlib/td#226]
I was testing my app adding and removing a user from administrators of my channel. After few iterations, I ended up with `getChatAdministrators` returning incorrect data:

![cloudapp annotation 2018-05-09 at 11 00 21 am png](https://user-images.githubusercontent.com/52201/39800298-50debe48-5378-11e8-801b-0f4106f368cc.png)

It's either TDLib cache problem or an issue on Telegram side. I'll be glad to help you to debug the issue, just tell me what to do. You can also contact me directly at Telegram: http://t.me/kossnocorp

**Comment by levlam** [comment]
Request to getChatAdministrators always returns result from a cache if possible, updating the cache in background. There is no update sent when cache value changes, because there is no way to make it reliable: client doesn't receive any update from the server when list of administrators is changed. So to receive actual list of administrators you need to repeat the call to getChatAdministrators in 1 second. Or better use getSupergroupMembers with filter supergroupMembersFilterAdministrators for supergorups (currently, it will always send network request) or getBasicGroupFullInfo for basic groups.

**Comment by kossnocorp** [comment]
> Request to getChatAdministrators always returns result from a cache if possible, updating the cache in background. There is no update sent when cache value changes, because there is no way to make it reliable: client doesn't receive any update from the server when list of administrators is changed. So to receive actual list of administrators you need to repeat the call to getChatAdministrators in 1 second. 

The thing is that TDLib is stuck in this state. I didn't try to add/remove the user from admins again in case if it could help to debug the issue.

> Or better use getSupergroupMembers with filter supergroupMembersFilterAdministrators for supergorups (currently, it will always send network request) or getBasicGroupFullInfo for basic groups.

Thank you for suggesting, I think I'll go with `getSupergroupMembers` as it doesn't rely on the cache.

**Comment by levlam** [comment]
If `getChatAdministrators` continues to return wrong result then `getSupergroupMembers` should also return the wrong result, because `getChatAdministrators` internally uses `getSupergroupMembers`, and this is a server-side issue. And if `getSupergroupMembers` returned correct result, then `getChatAdministrators` must also return it.

**Comment by kossnocorp** [comment]
Here is the result of `getSupergroupMembers` for the same chat:

![cloudapp annotation 2018-05-09 at 7 30 07 pm png](https://user-images.githubusercontent.com/52201/39824024-67f16e4a-53bf-11e8-8d40-3fb17ecdf86e.png)

As I understand the error means that the account has insufficient rights.

**Comment by levlam** [comment]
Is it a supergroup or a channel chat?

**Comment by kossnocorp** [comment]
@levlam sorry, I didn't notice your answer. This is a supergroup:

![cloudapp annotation 2018-05-17 at 11 35 15 am png](https://user-images.githubusercontent.com/52201/40162908-60515008-59c6-11e8-9e8e-4386740d4e72.png)

**Comment by levlam** [comment]
As I understand, you are creator of the channel. In that case you supposed to never get "Supergroup members are unavailable" error. It would be helpful if you collect TDLib logs with verbosity level 4 and send them to @tdlib_bot. Feel free to censor any sensitive data in the log before sending. If a problem with getChatAdministrators will also reproduce, then the same log will help to find its cause.

**Comment by kossnocorp** [comment]
> As I understand, you are creator of the channel. In that case you supposed to never get "Supergroup members are unavailable" error.

@levlam no, I'm not the creator. I have created this channel using my personal account and another one I use to authorize TDLib.

> It would be helpful if you collect TDLib logs with verbosity level 4 and send them to @tdlib_bot. Feel free to censor any sensitive data in the log before sending. If a problem with getChatAdministrators will also reproduce, then the same log will help to find its cause.

Ok, I'll do it.

**Comment by kossnocorp** [comment]
I didn't manage to reproduce the problem once again
