### ISSUE TITLE
Domain tdlib.t.me it's modern! TDLib now has a less modern domain core.telegram.org/tdlib

### ISSUE THREAD

**Issue by isopen** [tdlib/td#2261]
Bad domain for TDLib:
https://core.telegram.org/tdlib

Simple and beautiful domain for TDLib confirmed in The Open Network:
[https://tdlib.t.me](https://tdlib.t.me)
++ very easy to remember
++ fast keyboard typing
++ simple domain form - NFT
++ assigned to the owner in The Open Network
++ ability to use the short name [@tdlib](https://tdlib.t.me) in the Telegram environment (~700 million users)

I think anonymous suggestions on t.me might work: https://t.me/tonc_news/1151
Consider it as an option in the future. It would be cool for TDLib.
Fragment link: [https://fragment.com/username/tdlib](https://fragment.com/username/tdlib)

**Comment by AYMENJD** [comment]
The `t.me` short domain is meant for username resolve and for internal app usage.

The `core.telegram.org` is the correct domain since it meant for developers.

**Comment by isopen** [comment]
Disagree. The t.me domain is external. The core.telegram.org domain is also external.
tdlib.t.me is easier to remember than domain core.telegram.org/tdlib

**Comment by AYMENJD** [comment]
It is easy to remember, but not worthy.

There is many easy ways that could let you reach `core.telegram.org/tdlib` faster.

Having `tdlib.t.me` would need a lot of work.

Such as:
- buying the username from `fragment.com`.
- Configuring `t.me`,  which you and me doesn't know what they can do. Do they can easily move `core.telegram.org/tdlib` pages to `tdlib.t.me` without breaking anything? If they can't then they will make it redirects to `core.telegram.org/tdlib` which is not worthy.
- Documenting `tdlib.t.me` instead of `core.telegram.org` which break pages consistency.
- Repeating the same process with other names like `botapi.t.me`, `mtproto.t.me` etc.

It is better to be with [tg.dev/tdlib](https://tg.dev/tdlib).

**Comment by isopen** [comment]
Disagree. I hear about tg.dev/tdlib for the first time. tdlib.t.me is better for this (just in this case, the consistency of domain names is obtained)
For example: [t.me](https://t.me/) domain redirects to [telegram.org](https://telegram.org/)

**Comment by AYMENJD** [comment]
if [t.me](https://t.me) is the correct domain for developer related things it would've been redirect to [core.telegram.org](https://core.telegram.org) instead of [telegram.org](https://telegram.org).

**Comment by isopen** [comment]
Yes. Only in this case the "core" prefix is ​​superfluous.
[tdlib.t.me](https://tdlib.t.me) thematic for TDLib.

**Comment by AYMENJD** [comment]
Well, in my opinion it's not. It would only create inconsistency. And it will fix a useless issue.

**Comment by isopen** [comment]
At least that's the modern approach to using domain names.

**Comment by isopen** [comment]
@levlam Another way to use the [tdlib.t.me](https://tdlib.t.me) ([@tdlib](https://tdlib.t.me)) domain is official Telegram channel dedicated to TDLib functions.

**Comment by isopen** [comment]
![image](https://user-images.githubusercontent.com/7373292/221342676-82ec1730-0a02-4bf4-a5cd-83a3890cdecf.png)

**Comment by isopen** [comment]
![image](https://github.com/tdlib/td/assets/7373292/e747aedc-41cf-4eb5-82b1-dbaf299b95cc) ![image](https://github.com/tdlib/td/assets/7373292/71b0d2e7-150d-46f2-b584-34ee14474280)

**Comment by isopen** [comment]
@levlam web-apps are gaining popularity in Telegram.
https://t.me/tdlib may be just for this case.
