### ISSUE TITLE
TdApi problem

### ISSUE THREAD

**Issue by cheaterNo1** [tdlib/td#2279]
I got some errors with TdApi, I have imported:

package com.example.telegram_td;

import org.drinkless.td.libcore.telegram.TdApi;
import org.drinkless.td.libcore.telegram.Client;

![image](https://user-images.githubusercontent.com/46472572/213961361-b22938b9-3ffc-4169-a719-0c79c1f9e4bd.png)
and here is the problem:
![image](https://user-images.githubusercontent.com/46472572/213961415-c226dbf4-895f-46ed-9bbc-728531a08b3c.png)
could you support, thanks...

**Comment by levlam** [comment]
You seems to use prebuilt TDLib 1.8.0, which had only one parameter `parameters` in `setTdlibParameters`. See https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1set_tdlib_parameters.html or bundled javadoc documentation.

**Comment by PaperPlane28** [comment]
> 您似乎使用预构建的 TDLib 1.8.0，它`parameters`在`setTdlibParameters`. 请参阅https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1set_tdlib_parameters.html或捆绑的 javadoc 文档。

sir，the content in this address tdlibParameters is not the latest
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1tdlib_parameters.html
https://github.com/tdlib/td/blob/758ced943e44019b25852c365655da6f1fe6d24a/td/generate/scheme/td_api.tl#L5478

**Comment by levlam** [comment]
Yes. On-site documentation is for the latest pre-built Android version, i.e. 1.8.0.

**Comment by cheaterNo1** [comment]
As I understand it, either I have to prebuilt latest version myself or I have to find it somewhere. Could you update the lastest version to this link:
https://tdlib.github.io/td/build.html?language=Java, 
I am using Android studio, Thanks

**Comment by levlam** [comment]
Now you can use https://github.com/tdlib/td/tree/master/example/android to easily build TDLib for Android.

**Comment by cheaterNo1** [comment]
> Now you can use https://github.com/tdlib/td/tree/master/example/android to easily build TDLib for Android.

Actually it is a bit difficult to install many other software to build it, if you can provide the lastest, it is good and also good for many others like @PaperPlane28

**Comment by levlam** [comment]
If you develop for Android, you should already have most of the software installed.

**Comment by cheaterNo1** [comment]
I tried to build tdlib myself and got this:

![image](https://user-images.githubusercontent.com/46472572/215338753-31f4602f-068a-47ce-97ed-8c595993a536.png)

Should I copy CMakeLists.txt to /home ?

**Comment by levlam** [comment]
You should copy nothing. Clone the full TDLib repository and then run the scripts.

**Comment by cheaterNo1** [comment]
I coppied the full TDLib repository, but nothing change.

![image](https://user-images.githubusercontent.com/46472572/216067981-397de0f3-c2f2-40e9-9f9e-b29dcecadcb9.png)

**Comment by levlam** [comment]
You must not copy anything. Just clone the repository, enter the `td/example/android` directory and follow the instructions.

**Comment by cheaterNo1** [comment]
I have changed this code:
![image](https://user-images.githubusercontent.com/46472572/220744928-274afba7-c156-4738-8bb9-7657b92a97eb.png)

but it still throw:
![image](https://user-images.githubusercontent.com/46472572/220745245-c0421760-ef8f-4f39-a2e0-164d87374390.png)

help me please ^^

**Comment by levlam** [comment]
@cheaterNo1 
This is a Java error, not related to TDLib.

**Comment by PaperPlane28** [comment]
Sorry, I just saw this email
Although I am not using Java
but I know that there is a problem with the parameters you submitted
There seems to be a problem with the parameters you submitted ------ setTdlibParameters
https://github.com/tdlib/td/blob/1543c41f3411bd6aa74713c8aba4e93fa8d952c7/td/generate/scheme/td_api.tl#L5640


***@***.*** Sets the parameters for TDLib initialization. Works only when the current authorization state is authorizationStateWaitTdlibParameters
***@***.***_test_dc Pass true to use Telegram test environment instead of the production environment
***@***.***_directory The path to the directory for the persistent database; if empty, the current working directory will be used
***@***.***_directory The path to the directory for storing files; if empty, database_directory will be used
***@***.***_encryption_key Encryption key for the database. If the encryption key is invalid, then an error with code 401 will be returned
***@***.***_file_database Pass true to keep information about downloaded and uploaded files between application restarts
***@***.***_chat_info_database Pass true to keep cache of users, basic groups, supergroups, channels and secret chats between restarts. Implies use_file_database
***@***.***_message_database Pass true to keep cache of chats and messages between restarts. Implies use_chat_info_database
***@***.***_secret_chats Pass true to enable support for secret chats
***@***.***_id Application identifier for Telegram API access, which can be obtained at https://my.telegram.org
***@***.***_hash Application identifier hash for Telegram API access, which can be obtained at https://my.telegram.org
***@***.***_language_code IETF language tag of the user's operating system language; must be non-empty
***@***.***_model Model of the device the application is being run on; must be non-empty
***@***.***_version Version of the operating system the application is being run on. If empty, the version is automatically detected by TDLib
***@***.***_version Application version; must be non-empty
***@***.***_storage_optimizer Pass true to automatically delete old files in background
***@***.***_file_names Pass true to ignore original file names for downloaded files. Otherwise, downloaded files are saved under names as close as possible to the original name
setTdlibParameters use_test_dc:Bool database_directory:string files_directory:string database_encryption_key:bytes use_file_database:Bool use_chat_info_database:Bool use_message_database:Bool use_secret_chats:Bool api_id:int32 api_hash:string system_language_code:string device_model:string system_version:string application_version:string enable_storage_optimizer:Bool ignore_file_names:Bool = Ok;
