### ISSUE TITLE
Handling authentication code in third party apps

### ISSUE THREAD

**Issue by Kratos1013** [tdlib/td#2310]
Hello!

There are 3 new AuthenticationCodeTypes added :
1. AuthenticationCodeTypeFragment
2. AuthenticationCodeTypeFirebaseAndroid
3. AuthenticationCodeTypeFirebaseIos

2 and 3 are only for official Telegram client? So third party clients won't get this type of code?

If  NO then why third party app need Nonce for SafetyNet ?
If YES then how 3rd party client knows when user con not register new account?

Do we get error only when attempt to register new User? Or somehow we will get error while authenticating  user?

When exactly we have to request user to register via Official Telegram application?

Or third party client will never get AuthorizationStateWaitPhoneNumber?

Thank you!

**Comment by levlam** [comment]
> 2 and 3 are only for official Telegram client? So third party clients won't get this type of code?

Yes, they can't get it.

> Do we get error only when attempt to register new User?

For third-party apps authorization flow didn't change, except that `authenticationCodeInfo.type`/`next_type` can be only `authenticationCodeTypeTelegramMessage`, `authenticationCodeTypeFragment`, or null, which was a possible authorization flow previously.

Alternatively, third-party apps can immediately use `requestQrCodeAuthentication` instead of `setAuthenticationPhoneNumber` to log in users by QR code. Some additional options, which will simplify authentication in third-party apps, can be added in the future.

> Or third party client will never get AuthorizationStateWaitPhoneNumber?

All authorization states are reachable even for third-party apps. AuthorizationStateWaitPhoneNumber is documented as "Call setAuthenticationPhoneNumber to provide the phone number, or use requestQrCodeAuthentication or checkAuthenticationBotToken for other authentication options".

**Comment by Kratos1013** [comment]
Thank you very much!

**Comment by duwz82** [comment]
> 非常感谢！

hi, Is there a way for third-party applications to register telegram users through mobile verification code? Have you solved this problem?

**Comment by Flohack74** [comment]
So @levlam forgive slow perception of newest informations, but if I am on the test DC, with a phone no that has no account so far, and I use tdlib I still get only authenticationCodeTypeTelegramMessage. So it seems there is no way around using an official app first right?

**Comment by Flohack74** [comment]
I.e. users must use either the iOS or Android App to sign in for the first time? Somehow the conversation across a few tickets here left the impression that tdlib clients could still use SMS flow.

**Comment by aaalzya** [comment]
123800349

**Comment by levlam** [comment]
Only official Telegram mobile apps can authorize using an SMS now.

**Comment by Flohack74** [comment]
@levlam thanks, so for first-time users, if they try it on a 3rd party client, shouldnt the server refuse to register, since we know the code can never reach that device? we get Auth code type telegram message, but indeed that cannot be delivered at all, wouldnt be sending an error here a better solution?

**Comment by levlam** [comment]
This would allow to know intruders, whether the phone number is registered in Telegram. There is no way to find this before actually entering the authentication code.
