### ISSUE TITLE
registerDevice returns with error

### ISSUE THREAD

**Issue by vincentneo** [tdlib/td#2368]
I've realise that `registerDevice` recently is returning me an error, with code 400, and the message is `TOKEN_WAS_INVALIDATED`.

Device with observed issue is Apple Watch, watchOS 9.3.1.
`device_token` type is `deviceTokenApplePush`.
`other_user_ids` is sent with an empty array.

Notifications are not being received. 

What does that mean, and what can I do to remedy that?

**Comment by levlam** [comment]
The error is returned when APNS recently rejected provided token as invalid. When it is received, the app needs to ask OS for a new push notification token.

**Comment by vincentneo** [comment]
By the way, didFailToRegisterForRemoteNotificationsWithError 
https://developer.apple.com/documentation/watchkit/wkextensiondelegate/3141923-didfailtoregisterforremotenotifi

was never called either.

**Comment by levlam** [comment]
`registerForRemoteNotifications` each time returns the same already invalid token and the token must be refreshed by calling `unregisterForRemoteNotifications`, waiting a second, and then calling `registerForRemoteNotifications`. The server knows that the provided token is invalid, because APNS has returned an error when the server tried to use the token.

**Comment by vincentneo** [comment]
thanks for the advice, will try it out.

**Comment by vincentneo** [comment]
Yup that seems to have solved it!

Once again thank you very much @levlam!
