### ISSUE TITLE
'cstdint' file not found

### ISSUE THREAD

**Issue by liaoyu1992** [tdlib/td#238]
When I use tdlib in iOS, I can't compile it.Report the following error:`'cstdint' file not found `

**Comment by levlam** [comment]
It means that C++ standard library not found. 

Have you done `xcode-select --install` to install Xcode command line tools?
Have you tried to build TDLib using our [example](https://github.com/tdlib/td/tree/master/example/ios)?

**Comment by liaoyu1992** [comment]
Yes,I tried to build TDLib using example:
<img width="629" alt="image" src="https://user-images.githubusercontent.com/6285162/40049406-4be7a60e-5867-11e8-8de5-00484db9edb5.png">
I imported the library file from the iOS directory into Xcode, it.Report the following error:`'cstdint' file not found`

**Comment by levlam** [comment]
Which header files have you included in your project?

In fact, you shouldn't need <cstdint> to use JSON-interface, because you need to include only "td/telegram/td_json_client.h" and "td/telegram/td_log.h" like in the [Swift example](https://github.com/tdlib/td/blob/master/example/swift/src/td-Bridging-Header.h).

You can also try to enable С++11 support in project settings like advised in https://stackoverflow.com/questions/39521686/how-to-compile-a-project-with-c11-under-xcode-8.

**Comment by liaoyu1992** [comment]
thanks
