### ISSUE TITLE
Unable to undo authorizationStateWaitOtherDeviceConfirmation

### ISSUE THREAD

**Issue by Fra078** [tdlib/td#2433]
Using java, after sent command **requestQrCodeAuthentication** to display a qr code for login I'm unable to request phone number if the user change his mind and want to log in with phone number and code authentication

**Comment by levlam** [comment]
You can't call `setAuthenticationPhoneNumber` directly in the state `authorizationStateWaitOtherDeviceConfirmation`, because the other device can confirm authorization any time. It would be hard to distinguish, in what account the user was logged in. Instead, you need to call `logOut`, wait while the current authorization is canceled, and reopen the instance after the current instance closes.

**Comment by Fra078** [comment]
Thanks, I was doing in this way but I thought it was wrong
