### ISSUE TITLE
Question on tdlib logging & sensitive data

### ISSUE THREAD

**Issue by vincentneo** [tdlib/td#2530]
I know that the official Telegram app has a debug menu which includes the option "Remove Sensitive Data". 

Currently, as I am investigating an issue regarding Unread folders, I am kinda running out of ideas of why things are acting the way it is, so I was thinking of conducting some logging for the user. 

I do not wish to infringe on their privacy as much as possible however (i.e. I do not want to see their message contents, etc), so please advice is such options are available.

**Comment by levlam** [comment]
TDLib has no such option, because it is hardly possible to provide it and keep the log useful. The log contains much more private data then just message texts. Even if all strings and identifiers are anonymized somehow, there will be a lot more private data, like the users IP address, the time when they were online, types of the chats and messages, and much more.

**Comment by vincentneo** [comment]
Alright then, once again thank you for the insights!
