### ISSUE TITLE
Request for websites to reference "latest versions"

### ISSUE THREAD

**Issue by Reluctant-Dentist** [tdlib/td#2533]
I ask this because I've had trouble in the past and even got caught off guard by it recently.

I'm not sure if the dev team here has control over https://core.telegram.org/tdlib/docs , but if so, it is quite out of date. It looks like its still referencing version 1.8.0 which was released 2.5 years ago, a lot has changed since then. I understand keeping it in sync with the latest master is too much to ask, but even keeping up to date with the latest sub-version (Eg the first 1.8.14 commit, `8517026415e75a8eec567774072cbbbbb52376c1`) would help massively. Currently we have to dig through github files to find the updated docs which is a bit tedious. Especially for people who don't have a github account, since some pages require a login.

I also think a new tagged version on github for sub-versions would be good. I know the devs have said in the past that we should always use the latest master, however 2 weeks ago when I tried to build the latest version, I got compilation errors. I then tried the first 1.8.14 commit (2 months old at the time) and that worked, so it seems master wasn't working. A new tag should also help reduce the number of issues you get where people are using old versions, since some people tend to prefer tagged versions over latest master.

**Comment by levlam** [comment]
I agree that the on-site docs should be updated more often to reflect the latest changes in the API.

But in most cases documentation for the used TDLib version should be used instead. It is available in autogenerated API code files for C++, C# and Java interfaces, and is provided by many third-party wrappers for other programming languages. One can also use the source of the documentation at https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl. The file is always available locally after the repository is clonned.

> however 2 weeks ago when I tried to build the latest version, I got compilation errors.

This is unfortunate, but can happen sometimes, given the number of different existing C++ compilers. If master version doesn't build, you can create an issue and it will be fixed in no time.
