### ISSUE TITLE
In the official demo has a memory leak

### ISSUE THREAD

**Issue by liaoxingquan** [tdlib/td#2573]
td_example.cpp---------------------------------------------------------------------------------------------------
class TdExample {
	auto create_authentication_query_handler() {
		return [this, id = authentication_query_id_](Object object) {
			if (id == authentication_query_id_) {
				check_authentication_error(std::move(object));
			}
		};
	}
.......
}
int main() {
	TdExample example;
	example.loop();
}
-------------------------------------------------------------------------------------------------------------------
**My account has added many groups and a large number of messages have been received, resulting in a gradual increase in memory**

**Comment by levlam** [comment]
TDLib has no memory leaks, which you can check by closing the TDLib instance and using any tool for memory leak detection. 

The memory usage can grow over time, because TDLib has a cache which speeds up all requests and gives a big flexibility for the application. The cache contains data about all encountered users and chats and can contain some other data. The size of the in-memory cache can grow over time, so if app wants to flush it, it needs to close and reopen TDLib instance.

**Comment by levlam** [comment]
No. The only way is to call `close`, wait until the instance is closed, and opening another instance.
