### ISSUE TITLE
How to get chat message count of all types

### ISSUE THREAD

**Issue by neoedmund** [tdlib/td#2610]
We can use `getChatMessageCount` to get specified type of message count like videos, photos. But how to get the count of all types , and text message count?

**Comment by akulik512** [comment]
You have a`TdApi.Chat` object where you can take `lastMessage` and it has `id`.
If you divide this value by `1048576` (2^20) you will give the number of the last message. So we can say that this is a channel message number. 
But this may be far from reality. Because at any moment, someone can simply delete as many messages as they want and the number of the last message will not be changed.

**Comment by neoedmund** [comment]
A new created chat says it has 51K+ message according to your method, which seems like kidding. where your method comes from?

**Comment by levlam** [comment]
There is no way to receive total number of chat messages in TDLib.

**Comment by neoedmund** [comment]
Oh my ... but since "no way" is the answer, thanks and closing this issue
