### ISSUE TITLE
This library is open and allows many people to create their own Telegram, but why is it now easy to ban new accounts?

### ISSUE THREAD

**Issue by azkadev** [tdlib/td#2687]
I know userbots are not allowed on Telegram, but I tried to make my own Telegram GUI app using tdlib because the original Telegram design was boring, but is it easy to ban new accounts now? Does my application have to be big/famous first so that new accounts don't get banned?

**Comment by levlam** [comment]
If you have any issues with account banning in any Telegram app, then affected users need to try to log in from an official mobile app and send a email to recover the account by following instructions provided by the app. An official app is needed for this only because it contains up-to-date instructions for reporting the issue.
