### ISSUE TITLE
Slow startup time(5+ seconds)

### ISSUE THREAD

**Issue by ButbkaDrug** [tdlib/td#2721]
I'm suffering with a slow tdlib startup time. I build it using [instructions](https://tdlib.github.io/td/build.html). I'm building a cli tool so initial start time is crustal. It takes 5-6 seconds on average. I switched from debug to release build, but it hasn't change anything. Is there anything wrong that I'm doing??? Or maybe there is suggestions on how to improve startup time?

Just in case it is helpful:
OS: Pop!_OS 22.04 LTS x86_64
CPU: AMD Ryzen 5
Memory: 8 Gb

**Comment by levlam** [comment]
How do you run the app?

Do you have TDLib log enabled?

**Comment by ButbkaDrug** [comment]
It is a golang app. I use [zelenin's wrapper](https://github.com/zelenin/go-tdlib) for td lib. I'm not exactly sure what start up time should be, but basically as soon as I import tdlib wrapper(I tried other wrappers with the same result) cold run takes 5-6 seconds. Before even first request is made. If I build the app it's a bit better, but still takes around 2 seconds. I feel like it should be much quicker. But maybe it is normal...

I attach log file with verbosity level 5.
[kilogram.log](https://github.com/tdlib/td/files/13735361/kilogram.log)

**Comment by levlam** [comment]
In the log you can see that a TDLib's method is called first at 1703134355.376585721, the first request is received at 1703134355.378182411, instance is fully initialized at 1703134355.397875547. and even successfully connected to Telegram servers at 1703134355.615214347. So, initialization itself took less than 20 milliseconds. The issue is somewhere else, probably, in the wrapper's code. It is not normal to load a llibrary for 2-5 seconds.

**Comment by ButbkaDrug** [comment]
Thank you very much for your help.  Highly appreciate it.
