### ISSUE TITLE
Threading issue with addProxy

### ISSUE THREAD

**Issue by wizche** [tdlib/td#2766]
Hi,

I'm cross-posting an issue from the C# binding since it seems related to the tdlib.
[Link to the issue in tdsharp](https://github.com/egramtel/tdsharp/issues/186)

Basically it looks like that the `addProxy` call only returns when not being executed from the main-thread.
Thanks a lot

**Comment by levlam** [comment]
`AddProxy` will return response after the request will be completed, no matter from which thread it is sent. But the request can't be complited before the TDLib instance is initialized (`SetTdlibParameters` is called). If the request isn't return, then it is because `SetTdlibParameters` is never called.

**Comment by levlam** [comment]
It is better to call `AddProxy` before `SetTdlibParameters`. This is supported and intended order of the calls, otherwise you may try to connect without proxy first. But you must not wait synchronously for `AddProxy` response. Waiting synchronously for request response is a bad idea most of the time.
