### ISSUE TITLE
Large growing native memory usage by the Java app which uses tdlib

### ISSUE THREAD

**Issue by andreymerchenko** [tdlib/td#2807]
Dear tdlib community,

In my java application there can be multiple telegram accounts (i.e. multiple org.drinkless.tdlib.Client instances).
I am checking the memory usage of the app and I see that the heap, threads, metaspace don't grow and remain on the practically the same level. However, the native memory of the process grows. And at some point in time the process runs out of memory on the host and the application becomes unresponsive (and this is not Java out of memory, it does not occur). Used heap memory is only around 10% of the native memory.
The application uses messages databases ('useMessageDatabase' parameter is set to true) and listens to Telegram updates on accounts, chats and messages. 
I am aware that once the native memory is reserved by the process it cannot be freed, only reused. So I am currently searching for ways to decrease the amount of native memory being used and make it not grow until it occupies the whole memory on the host.

I tried to close the clients, however looks like the native memory was not reused but continued to grow when the clients were loaded again.

The issue with native memory growth is reproducible even in idle mode when the application only listens to updates from Telegram and no actions are performed.

There are no other parts of this Java application which could heavily occupy native memory (there are no other native method invocations other than the tdlib ones), thus I suppose this native memory is used by tdlib/sqlite.

Could you, please advise on the following questions:
1. Why wasn't the native memory, which was expected to be freed, not be able to be reused when the clients were closed and then loaded back?
2. Are there any known incorrect usages of tdlib library which could lead to such behavior?
3. Are there any approaches (maybe some library configurations) to decrease the amount of native memory being used?

Thank you.

**Comment by andreymerchenko** [comment]
Hi @levlam , thanks for the quick response!

1. Attaching a graph of the native memory usage when 100 Telegram users are used:
![image](https://github.com/tdlib/td/assets/158522502/1251339c-311e-4328-8cc4-89c73bafb37f)
1-2. Application was in idle mode with just 100 clients listening for updates. We can see steady growth of used memory (~18MiB/h)
2-3. Application was working without any clients open. We see constant memory usage.
3-4. Once the same 100 clients are loaded again, we see a jump in memory consumption ~200MiB and then constant growth (~18MiB/h).
4-5. Stop and loading of clients after 1-2mins adds 58MiB to memory usage.
5-6. Stop and loading of clients after 1-2mins adds 36MiB to memory usage.

2. Client requests are sent from different types of threads: for example, in case of web requests these are short-living threads, and there are cases when Client.send requests are sent from the threads in the thread pool and can be reused. Does it make any difference whether Client.send requests are performed from short-living threads or from pooled threads.

**Comment by levlam** [comment]
1. Memory growth should be slower and slower over time. You can see that on the graph, but this also could be caused by the night time.
180kb of new data per hour per client isn't a lot for more workloads.
10MB of data per new instance is also fine if the whole chat list isn't loaded. Otherwise, ot should be less than 1MB.
Memory growth on client reopening is likely caused by memory fragmentation within native allocator. You need to hook the allocator itself or ask him for statistics to see real memory usage. It should decrease slightly right after close/reopen.

2. Sending requests from short-living threads may affect memory usage, because some thread-local data can be allocated by TDLib for each thread.

**Comment by andreymerchenko** [comment]
1. We see at point in time 1(on the graph) that those 100 clients are already loaded and occupy some memory, then memory consumption is growing till point in time 2 and at that time those 100 clients are occupying also some memory, lets name that memory as X. I am under impression that when we close those 100 clients, most of those X should be free and when after 1 hour we start the same 100 clients again then should reuse that X memory that is free at that moment of time and that will take some time for them to occupy the same X of already allocated memory for application, however they start occupying X+400MiB **right after they are started**. If we close them and open they start occupying X+460 if we close and open them - X+500. 
Is that expected behavior?
As eventually that leads to usage of 100% memory on the device without any possibility to free some memory without restarting the app.
2. Is there any cross-client shared cache that is not being cleaned up when we close those 100 clients?

**Comment by levlam** [comment]
1. This is correct, but memory must be allocated in continuous segments and very often native allocators can't reuse previously freed memory. In this case they are forced to allocate new memory from OS, but some memory is reused. That's why you see only +400 MiB instead of +1GB. To correctly check used native memory you need to ask the allocator. This can't be measured externally. And yes, memory [fragmentation](https://en.wikipedia.org/wiki/Fragmentation_(computing)) can lead to ever growing memory usage.
2. There is, but it is small and of bounded size. Some objects are instantiated only once per app lifetime and can be shared between instances.
