### ISSUE TITLE
How i can get current user profile pic?

### ISSUE THREAD

**Issue by Mashi-91** [tdlib/td#2875]
![Screenshot 2024-05-07 164957](https://github.com/tdlib/td/assets/56748946/25081300-c0d7-411e-9290-08e0a41d70b9)

Showing this error

flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   TelegramClient.downloadUserProfilePhotoUrl (package:CloudInfinity/data/vider/tdlib.dart:145:22)
flutter: │ #1   <asynchronous suspension>
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ ⛔ Something Else Wrong: 404
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by levlam** [comment]
Profile photo of a user can be accessed using the field `user.profile_photo`. It is of the type `ProfilePhoto` with the following fields:
`profilePhoto id:int64 small:file big:file minithumbnail:minithumbnail has_animation:Bool is_personal:Bool = ProfilePhoto;`

You don't need to use `getFile`, because you already have the file object in the `profilePhoto`. You can download the photo by passing the `fileId` to `downlaodFile`.

Attempts to mix TDLib API and Bot API calls makes no sense and have no chance to work.

**Comment by Mashi-91** [comment]
thnx
