### ISSUE TITLE
Telegram giriş yapılmıyor 

### ISSUE THREAD

**Issue by Beyfendix** [tdlib/td#2988]
![Screenshot_20240716-171121285](https://github.com/user-attachments/assets/0aa83cfc-05cc-4e32-b717-e71abee34f19)
Merhaba bu sabah uyandığımda böyle bir hata aldım sebebi nedir yardımcı olur musunuz?

**Comment by levlam** [comment]
Share error details with https://t.me/tdlib_bot using the button from that screen.

**Comment by Beyfendix** [comment]
Hangi butonu

**Comment by levlam** [comment]
There is a button "Hata ayrıntılarını paylaş" on that screen.

**Comment by Beyfendix** [comment]
Tamam da paylaşılmiyor neden böyle ya lütfen yardımcı olun

**Comment by levlam** [comment]
You must send error details to the bot through another app, or at least send them there.

But the app crashed because of a hardware error with flash drive on your phone, that can happen when the disk or file system are broken. You can try to press "Launch app" button a few times. If this doesn't help, then only app reinstall can help, but given this is a hardare issue, it is likely to return after some time.

**Comment by Beyfendix** [comment]
Bot cevap vermiyor
