### ISSUE TITLE
Update macOS build instructions

### ISSUE THREAD

**Issue by ip** [tdlib/td#311]
https://core.telegram.org/tdlib/docs/index.html#building

> Build TDLib with CMake as explained in building. You may need to manually specify path to the installed OpenSSL to CMake

"may need" should be replaced by "must", because some people (including me) make the same mistake while building the library, see https://github.com/tdlib/td/issues/110#issuecomment-369550590

**Comment by levlam** [comment]
"may need" is there, because this highly depends on how OpenSSL was installed, on CMake's FindOpenSSL module and many other things. On macOS the path usually needs to be specified manually to CMake, so we drew attention to that. I will replace "may need" with "will likely need" to emphasize that it is often the case.

**Comment by Bannerets** [comment]
For me on macOS CMake successfully finds openssl without manually specifying path
