### ISSUE TITLE
TDLib crashes when compiled with OpenSSL 3.4.0

### ISSUE THREAD

**Issue by vincentneo** [tdlib/td#3171]
Crashes after first few updates are received.

<img width="1885" alt="Crash at line 954 of crypto.cpp (int err = PKCS5_PBKDF2_HMAC(password.data(), narrow_cast<int>(password.size()), salt.ubegin(),...)" src="https://github.com/user-attachments/assets/bc77f953-ec9e-4cbe-8540-2b4212c69db7">

Looking at crash location, I suspect it's an incompatibility with OpenSSL 3.4.0. Will confirm later by recompiling using 3.2.2 which is a known good version.

Information:
- TDLib 1.8.41, c85b20a
- OpenSSL 3.4.0
- Tested on watchOS 11.0

**Comment by vincentneo** [comment]
When compiled with OpenSSL 3.2.2, as expected TDLib 1.8.41 works fine.

**Comment by levlam** [comment]
The trace point to internals of the OpenSSL, which highly likely makes the bug an OpenSSL 3.4.0 bug. To confirm this and remove other possible causes a minimal example is required. Could you build the code
```
#include <openssl/evp.h>

void test_pbkdf2() {
  unsigned char buf[32];
  unsigned char salt[4];
  salt[0] = salt[1] = salt[2] = salt[3] = 's';
  PKCS5_PBKDF2_HMAC("password", 8, salt, 4, 2, EVP_sha256(), 32, buf);
}
```
, call the function from your code without loading TDLib and check whether it crashes?

**Comment by vincentneo** [comment]
Indeed it crashes too. 

<img width="1380" alt="Screenshot 2024-12-07 at 12 59 59 AM" src="https://github.com/user-attachments/assets/a5d47ded-f881-4c03-8fa4-35b8df3e7dbb">
Project used to run can be found in this repo: https://github.com/vincentneo/OpenSSL340Crash

**Comment by levlam** [comment]
Does it crash only for some specific architecture?

**Comment by vincentneo** [comment]
I think so as it didn't crash on the watchOS simulator (arm64). It only crashed on the watch device (arm64_32)

**Comment by levlam** [comment]
Could you show the exact place of the crash in `ossl_ht_get` function?

**Comment by vincentneo** [comment]
<img width="1264" alt="Screenshot 2024-12-07 at 11 35 48 PM" src="https://github.com/user-attachments/assets/4999993d-d50f-42b4-84f9-24993cf1b64c">

Perhaps I should rebuild this with dSYMs or something

**Comment by levlam** [comment]
Could you do the last test before this can be properly reported to the OpenSSL team? Could you rebuild OpenSSL 3.4.0 with `-DUSE_ATOMIC_FALLBACKS` and check whether this fixes the issue?

**Comment by vincentneo** [comment]
Sorry but can you advise where to add `-DUSE_ATOMIC_FALLBACKS`? I'm using the Python-Apple-Support script in the examples, with the version number modified for 3.4.0. Thanks.

**Comment by levlam** [comment]
The Makefile has the line
> CFLAGS-watchOS=-mwatchos-version-min=$(VERSION_MIN-watchOS)

which can be replaced with
CFLAGS-watchOS=-mwatchos-version-min=$(VERSION_MIN-watchOS) -DUSE_ATOMIC_FALLBACKS

**Comment by vincentneo** [comment]
Thanks will do

**Comment by vincentneo** [comment]
Looks like that solves it - the minimal example didn't crash

**Comment by levlam** [comment]
Thank you. Now we have enough data to be sure that this is an OpenSSL 3.4.0 bug and what causes it. OpenSSL introduced a new hashtable implementation this year, which didn't exist in 3.3.0 and was merged to 3.4.0. The crash happens on the first access to the hashtable, so I don't think that the specific called OpenSSL method matters. It is likely that the implementation of the hashtable is incorrect for `arm64_32`, which wasn't catched by regular OpenSSL tests. Given, the position of the crash it looks like the bug is actually in atomics implementation in the OpenSSL. Namely, in the function `apple_atomic_load_n_pvoid` introduced in the commit f5b5a35c84626823364b0c8535b968c106690a56. The bug affects only `arm64_32`.

Now we need to create an issue at https://github.com/openssl/openssl/issues. Do you want me to describe the issue to them or do you want to do this yourself?

**Comment by vincentneo** [comment]
Ah I see. Thanks for the explanation.

I think you understand the problem better than I do, so I think it would be better if you describe the issue to them. If subsequently they need any more data then I can help to provide.

**Comment by vincentneo** [comment]
Closing this as issue is fixed by https://github.com/openssl/openssl/commit/038b0f6b996d267c1a2da80ab7026bf01990875b
