### ISSUE TITLE
elementary os cmake failed

### ISSUE THREAD

**Issue by pytimer** [tdlib/td#323]
Hi, i am beginner for this.

Now i have a problem when i run `cmake -DCMAKE_BUILD_TYPE=Release ..`.
I already install dependencies, but it also `cmake` failed, error log like below:
```
Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8")
-- Found ZLIB: /usr/include /usr/lib/x86_64-linux-gnu/libz.so
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIR)
CMake Warning at CMakeLists.txt:248 (message):
  Not found OpenSSL: skip TDLib, tdactor, tdnet, tddb

-- Configuring done
-- Generating done
```

i search this problem on the internet, someone said should install `libssl-dev`, and when i installed, `cmake` successfully. So i think whether add `libssl-dev` in [installing-dependencies](https://github.com/tdlib/td#installing-dependencies) if `cmake` on the Linux?

**Comment by levlam** [comment]
We just said "Install all dependencies using your package manager" for Linux, because there are too much different Linux distros which have very different package management systems and can have very different names for the same package. So there is no way to cover all Linux distributions and Linux user usually knows better, how to install OpenSSL, zlib, cmake, C++14 compiler and gperf on his system.

**Comment by pytimer** [comment]
Thanks for your reply. I understand, I will close this issue.
