### ISSUE TITLE
Search supergroup by name and get supergroup members

### ISSUE THREAD

**Issue by pytimer** [tdlib/td#324]
Hi,

I want search supergroup by group name, and get all members of the supergroup.

my code flow like below:

- step 1: call  `SearchChatsOnServer` get chats
- step 2: call `GetChat` get one chat info
- step 3: call `GetSupergroupMembers` get all members.

i find the chat id is int64, but when call `GetSupergroupMembers` function, it need int32, so i want to know how to convert it? Or my step is wrong?

**Comment by levlam** [comment]
Each `Chat` has a type.  If a type of a chat is `ChatTypeSupergroup`, it has `supergroup_id` there, which should be used in `GetSupergroupMembers`.

**Comment by pytimer** [comment]
Thanks.
I find you said, but i should check `Chat` type on my code and deal with different. Does it have the same function to get id?

**Comment by levlam** [comment]
What do you mean? Only `ChatTypeSupergroup` has `supergroup_id`. For other types of chat members should be received in a different way.

**Comment by pytimer** [comment]
Sorry, i make a mistake. You said right.

I have another problem. I get supergroup members, and then i add members to my other group, it can only add a part of members, and no error in log file. Why?

**Comment by levlam** [comment]
There can be a lot of reasons for that. For example, these users could use privacy settings to disallow adding them to groups by non-contacts.

**Comment by levlam** [comment]
1. There is no way you can check it, because you have no access to others privacy settings. If you can't add someone, then it is expected and not a bug.

2. Test DC is not related to main DC in any way. It has completely different set of users and chats. You can register new account there on the same phone number for testing purposes.

**Comment by pytimer** [comment]
> There is no way you can check it, because you have no access to others privacy settings. If you can't add someone, then it is expected and not a bug.

I asked the group administrator, thers is no special settings. But this group creator can not add other members to administrator, it is very strange, do you know why?

> Test DC is not related to main DC in any way. It has completely different set of users and chats. You can register new account there on the same phone number for testing purposes.

How to register new account, i delete my account and use my phone number to register account, but when my program use test DC, it is still need to input verification code. Is it only possible to run the program and then receive SMS code to register? Can not register first?

**Comment by levlam** [comment]
These are users privacy settings. Users restricted set of accounts, which can add them to groups.
If creator can't add administrators, then he is spam-blocked. He can write to @spambot to see that.

I can repeat again, that in test DC you can register completely independent account in completely independent environment. There is no way it can send code to the account registered in production DC. In order to register new account you need to specify non-empty first_name in `checkAuthenticationCode`.
