### ISSUE TITLE
Exclude specific chat identifiers in GetStorageStatistics

### ISSUE THREAD

**Issue by vkryl** [tdlib/td#331]
It would be nice if there would be an option to calculate storage statistics via `GetStorageStatistics`, ignoring optionally specified `long[] excludeChatIds` to get results faster, when statistics calculation for specific chats is not needed.

**Comment by levlam** [comment]
It will not increase speed of `getStorageStatistics`, because most of the time is spent on scanning folders with files on hard disk and scanning file database. There is no way we can skip files from specific chats while this scan is done. It could help only if files from different chats were stored in different folders.
