### ISSUE TITLE
Functions are too hard to store

### ISSUE THREAD

**Issue by KnightNiwrem** [tdlib/td#343]
I'm getting this during the cmake compilation step, and I'm not sure what it means.

```
[ 29%] Generate common tl source files
Function initConnection is too hard to store
Function invokeAfterMsg is too hard to store
Function invokeAfterMsgs is too hard to store
Function invokeWithLayer is too hard to store
Function invokeWithoutUpdates is too hard to store
Function initConnection is too hard to store
Function invokeAfterMsg is too hard to store
Function invokeAfterMsgs is too hard to store
Function invokeWithLayer is too hard to store
Function invokeWithoutUpdates is too hard to store
Function initConnection is too hard to store
Function invokeAfterMsg is too hard to store
Function invokeAfterMsgs is too hard to store
Function invokeWithLayer is too hard to store
Function invokeWithoutUpdates is too hard to store
[ 29%] Built target tl_generate_common
```

The resulting libtdjson.so generated also seems to cause a Segmentation Fault when I try to use to initialize a connection. Would appreciate any help here!

**Comment by KnightNiwrem** [comment]
This issue seems to be related to incompatible OpenSSL library used by NodeJS and TDLib. Changing to an older version of NodeJS (v8.x) seems to resolve the Segmentation Fault issue.

Though, I'd still be curious about those compilation errors.

**Comment by levlam** [comment]
"Function invokeWithoutUpdates is too hard to store" is information message meaning that the code for storing some TL objects wasn't generated automatically. It is harmless.

OpenSSL 1.1.* and OpenSSL 1.0.* are binary incompatible. All libraries used in an application must be compiled with the same minor OpenSSL version, otherwise you will get random Segmentation Faults. If you use TDLib from Node.JS, you need to build it with the same OpenSSL version that was used to build Node.JS.

**Comment by KnightNiwrem** [comment]
All right. Thanks for the information!

**Comment by mib32** [comment]
@levlam So you are saying that OpenSSL 1.1.* and OpenSSL 1.0.* are incompatible with TDLb?

**Comment by mib32** [comment]
@levlam Sorry, checked https://github.com/tdlib/td/issues/259 and understood.
