### ISSUE TITLE
API for online members count in groups

### ISSUE THREAD

**Issue by vkryl** [tdlib/td#390]
For now, the only way to display online count in supergroups & groups is to request members list, do proper caching, listen for online updates for these members & update UI accordingly.

While it's quite easy to do this for basic group manually by client, it becomes pretty tricky to properly manage it for supergroups from client side.

This could be done in a better way by TDLib using internal & database cache.

For example, there could be `GetChatActiveMemberCount` method & `updateChatActiveMemberCount`, which could be sent when the chat is open (i.e. `OpenChat` called properly).

This would also be useful in case when there will be server-side improvements for online member count: no changes will be needed by clients.

**Comment by levlam** [comment]
There is no way it can be done for big supergroups.
First of all, user can't receive updates about online statuses of all supergroup members, because it will require too big amount of traffic, will create enormous server-side load and will make the whole app too slow. Caching list of chat members will not help either, because most chat member statuses will be outdated in the cache. So the only way to make it work client-side is to reget from time to time the whole list of chat members. This method also requires a lot of traffic, so it can be done only for small groups. `GetChatActiveMemberCount` can be useful, but it will not work in many chats anyway and will require under the hood a lot of traffic. Currently, this method doesn't exist, because I don't want to hide this complexity (it will be very unexpected for users of this method, that to receive one number a server request with result size of tens of kilobytes even for small groups is required) and add a method which can't work reliably anyway.

Adding `updateChatActiveMemberCount`, which will be sent from time to time for some opened chats, sounds more reasonable, because TDLib can control for which chats this feature works and that number of server-side requests is small enough.

**Comment by levlam** [comment]
This is available in TDLib 1.4.0 via the new update `updateChatOnlineMemberCount`.
