### ISSUE TITLE
Allow authentication for bots without api_id and api_hash

### ISSUE THREAD

**Issue by x2bool** [tdlib/td#426]
TDLib is really useful for bot programming. The only downside is that the programmer has to provide api_id and api_hash. As I understand they are not needed for Bot API. Please consider making these params optional for bots.

**Comment by delivrance** [comment]
@x2bool The API key (api_id and api_hash) is always needed when dealing with MTProto; it's an API requirement and can't be made optional. TDLib in the HTTP Bot API backend simply uses its own API key that's hidden from the public, that's why you don't have to pass it. Some little more details [here](https://github.com/pyrogram/pyrogram/issues/173#issuecomment-446569993).

In short: the API key identifies your application, the bot token identifies your bot as a "user" (in place of the phone number for normal users).

**Comment by x2bool** [comment]
@delivrance Thanks for the explanation. But still, this is a little bit inconvenient.

**Comment by levlam** [comment]
As @delivrance explained, there is no way to connect to Telegram servers without api_id/api_hash. And we can't make Bot API's api_id/api_hash public or publish any other api_id/api_hash to be used with bots only, because it defeats primary purpose of api_id. api_id should be bound to a specific Telegram application, regardless of whether the application is intended for ordinary users or bots.
