### ISSUE TITLE
td/telegram/MessagesManager.cpp is way too big

### ISSUE THREAD

**Issue by minlexx** [tdlib/td#441]
File td/telegram/MessagesManager.cpp is way too big (27k source lines, seriously?) and causes a compiler to fail with "virtual memory exhausted" error when compling for `armv7` architecture with standard `-O2` flag. Compiler (gcc) process tries to consume more than 4 Gb of RAM and fails to do that on 32-bit.

I suggest you try to split into several smaller parts (at least to ~27 smaller parts).

**Comment by levlam** [comment]
Yes, it is. Telegram is a messenger, so there is a lot of code, which deals directly with messages. MessagesManager size was reduced by 15% in a private version by moving out some components, but it can't be reduced significantly more without making classes Message and Dialog effectively public. That is a С++ restriction, which lacks notion of "package private" classes.

The problem with too big compiler memory comsumption was also solved. Next version will need less than 1 Gb RAM for g++ and less than 500 Mb for clang.

Between, you are wrong that the file needs a lot of RAM to compile just because it is big. Some standard С++ headers are bigger than it and after preprocesing source of MessagesManager own code is less than 20% of the compiled unit. The main problem was in very poor implementation/design of std::unique_ptr.

Splitting the file to ~27 smaller parts will also help, but total compilation time will be increased significantly, approximately in 27 times for that file,

**Comment by minlexx** [comment]
Well, I have to say, I got it to compile with `-O0` instead of `-O2` and removing `-pipe` from `CXXFLAGS`.

> The problem with too big compiler memory comsumption was also solved.

I'm curious, how?

> Between, you are wrong that the file needs a lot of RAM to compile just because it is big.

Well, but gcc docs say exactly that - https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html ` Optimizing compilation takes somewhat more time, and a lot more memory for a large function. ` Guess that's why `-O0` helped me.

> Splitting the file to ~27 smaller parts will also help, but total compilation time will be increased significantly,

At least, it would be possible to compile it 😜 

> Next version will need less than 1 Gb RAM for g++ and less than 500 Mb for clang.

OK, if you are sure about that (is it in git master here?) - then we can probably close this issue. Thanks.

**Comment by levlam** [comment]
Let's keep this issue open, until these changes are published. It is unfair to close it before they are publicly available.

**Comment by levlam** [comment]
TDLib 1.4.0 which can be build with much less RAM usage is published.

Also see a [TDLib build instructions generator](https://tdlib.github.io/td/build.html) for the exact build instructions.
