### ISSUE TITLE
Title for the chat with myself, aka Saved Messages

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#459]
Currently TDLib names chat with myself as combination of first and last name.  `setChatTitle` to change it to "Saved Messages" won't help, because it does not work with private chats.  Currently I synthetically show it as "Saved Messages" in chat list.  However this approach has downside, such as this chat is not searchable for example with `searchChats` query="Saved".  Official client somehow does it correctly, i.e. it appears in search results for "Saved".

What is the correct approach to have "Saved Messages" title (or maybe some custom title) for the chat with myself, so TDLib will know about it?

**Comment by levlam** [comment]
The name of that chat depends on a used localization, so it is "Saved Messages" in English and something else in other languages. Setting title of private chats isn't implemented yet in TDLib, so for this chat a string from a language pack should be shown instead of the chat name. This chat also requires special handling for search, because it can be found by first name + last name + username, or by "Saved Messases", or by native name. This is also not supported by TDLib yet, so search for the last two string is done client-side.

I plan to support `setChatTitle` for private chats in the future, but there is no ETA for this feature.

**Comment by zevlg** [comment]
Thanks for the clarifications!
