### ISSUE TITLE
How to get user_id by phone number without ImportContacts

### ISSUE THREAD

**Issue by Salardx** [tdlib/td#483]
Other than ImportContacts, Is there anyway to know the user_id by phone number?
Or at least a way to realize that a phone number is registered in telegram or not...

**Comment by levlam** [comment]
There is no method in the Telegram API, which is supposed to return this information because of privacy concerns. ImportContacts and some other methods return user_ids by a phone number as a side effect, but all such methods are subject to very tight server-side flood control, which prevents them from such usage.

**Comment by Salardx** [comment]
Okay, at least is there any method to show up whether a phone registered in telegram or not?

**Comment by Salardx** [comment]
> 
> 
> There is no method in the Telegram API, which is supposed to return this information, because of privacy concerns. ImportContacts and some other methods return user_ids by a phone number as a side effect, but all such methods are subject to very tight server-side flood control, which prevents them from such usage.

Could you please mention a valid link or reference about those tight server-side controls?

**Comment by Salardx** [comment]
Thanks, How bad are those tight flood controls? How long does it take for telegram to get rid of it? How long after would telegram put the victim into whitelist?

**Comment by levlam** [comment]
They are very tight. That's all I can tell.

**Comment by levlam** [comment]
The correct approach is to create a special bot, which will send the image of the receipt, to users and use [Telegram login widget](https://core.telegram.org/widgets/login) on the site to allow users to subscribe for receipt receiving through the bot.

**Comment by Salardx** [comment]
Yeah, it might be a workaround, but the customers I'm talking about mostly do not care about bots or more precisely do not trust them. in other words, they'd prefer to get in touch with real persons. Is there any other approach other than utilizing bots?

**Comment by Salardx** [comment]
Like, say, what happens if I call ImportContacts once every 6 hours and add 3 to 5 contacts every time. I mean my customers (those who are newcomers) would have to wait 6 hours to get added into account. and then I'd send the images to them.

**Comment by zelenin** [comment]
@Salardx, @levlam wants to say that this library is for writing clients for humans, not for automatic bots. Accordingly, the limits should be similar to human behavior without specific numbers. Limits are not the concern of `tdlib`.

**Comment by Salardx** [comment]
> 
> 
> @Salardx, @levlam wants to say that this library is for writing clients for humans, not for automatic bots. Accordingly, the limits should be similar to human behavior without specific numbers. Limits are not the concern of `tdlib`.

I understand, but my customers want human too...

**Comment by levlam** [comment]
@Salardx There is no other approach, because such tasks are supposed to be automatically done by bots without any delays and restrictions after user willingly subscribes for receiving messages from the bot. Your approach with ImportContacts will completely stop working in a few hours or a few days. Corresponding user account can be also blocked for spam if any user report it.

**Comment by pabx06** [comment]
use signal ?
