### ISSUE TITLE
Web browser in the browser and TDLib

### ISSUE THREAD

**Issue by isopen** [tdlib/td#508]
Guys. Does anyone have a implementation in web worker?
https://github.com/tdlib/td/issues/18

**Comment by levlam** [comment]
You can see one such implementation in https://evgeny-nadymov.github.io/telegram-react/. We will make corresponding npm package public after it is fully-documented and we implement other pending TDLib tasks.

**Comment by isopen** [comment]
Great example of use, but there are moments. For example, the CPU load is 100% after reloading the page.
The first start on a mobile device is very long. On the PC, the first launch is also not fast.
Maybe we should think about lazy loading? (If it is even possible in this case)

**Comment by levlam** [comment]
TDLib 1.4.0 includes an [example](https://github.com/tdlib/td/tree/master/example/web) of TDLib usage in a browser. You can also use NPM package [tdweb](https://www.npmjs.com/package/tdweb) if you don't want to build TDLib yourself.

**Comment by theChengundertheQun** [comment]
@isopen hey, I got a new problem, I just like [ https://evgeny-nadymov.github.io/telegram-react/](url) to use tdweb, but when I run my project, I just got a error in my console:
**Manifest: Line: 1, column: 1, Syntax error.
Uncaught SyntaxError: Unexpected token '<'**
And I think it is because teweb.js line 231: new Worker(xxxx.worker.js), but I have no idea how to fix it.
And I use create-react-app to create my project.
So have any idea about that?
Thanks for your time

**Comment by isopen** [comment]
Mode wasm or js?

**Comment by theChengundertheQun** [comment]
> Mode wasm or js?
js

**Comment by isopen** [comment]
js slows down more than wasm. I use wasm in my project

**Comment by theChengundertheQun** [comment]
ok, thanks anywhere

**Comment by theChengundertheQun** [comment]
> js slows down more than wasm. I use wasm in my project

Wait, I use the npm tdweb, and the tdweb.js import the wasm.

**Comment by oliverox** [comment]
> @isopen hey, I got a new problem, I just like [ https://evgeny-nadymov.github.io/telegram-react/](url) to use tdweb, but when I run my project, I just got a error in my console:
> **Manifest: Line: 1, column: 1, Syntax error. Uncaught SyntaxError: Unexpected token '<'**
> And I think it is because teweb.js line 231: new Worker(xxxx.worker.js), but I have no idea how to fix it.
> And I use create-react-app to create my project.
> So have any idea about that?
> Thanks for your time

This issue is because you are trying to load your service worker file from a different root directory. Since you are using create-react-app, you need to make sure your service worker is being placed in your 'public' folder and can be accessed by pasting its full url in the browser. If you can't access it, then you'll see the error you are seeing because create-react-app tries to load index.html first. Nothing to do with manifest issue.
