### ISSUE TITLE
Dart/Flutter implementation

### ISSUE THREAD

**Issue by ghost** [tdlib/td#516]
Is adding to Flutter possible at this point?

**Comment by levlam** [comment]
It should be pretty easy to write Dart Native Extension for [TDLib JSON interface](https://github.com/tdlib/td/blob/master/td/telegram/td_json_client.h), which contains only a few simple С methods.

It seems that using TDLib through JSON interface from Dart will be also possible without writing a Native Extension through an FFI in a few months: https://github.com/dart-lang/sdk/issues/34452.

**Comment by isopen** [comment]
eg dart: #566

**Comment by arthur109** [comment]
Hey! Lots of people are depending on this, especially now that flutter is growing so fast. How long do you think it will be until we have a proper dart implementation?

**Comment by levlam** [comment]
@arthur109 TDLib provides a very simple C interface which can be easily used from almost any programming language, including Dart. Still Dart is somehow special, because third-party wrappers where created almost instantly for 15+ other popular programming languages, but there is no public Dart Native Extension/Flutter Plugin for TDLib written by Dart community.

Dart recently added [early preview support for FFI](https://github.com/dart-lang/sdk/issues/34452#issue-359602269 ), which simplifies usage of TDLib from Dart even more. There is already a [Dart wrapper for TDLib](https://github.com/tdlib/td/pull/566/commits/cbe26809aa674bf71aa17bb781d5bf6a6e6fbd38), written by @isopen using Dart FFI.

**Comment by levlam** [comment]
Some more Dart wrappers for TDLib were created recently. For example, see https://github.com/tdlib/td/blob/master/example/README.md#dart.

**Comment by isopen** [comment]
Stoyamba `Levsky`. In ffi from `Dart` `ffi.allocate` fell off. I will try to fix it.
