### ISSUE TITLE
API ID Causing Bans

### ISSUE THREAD

**Issue by MarcFreeman** [tdlib/td#534]
It seems that the API information on the C# example is banned by telegram and causes accounts to be deleted.  I’ve successfully reproduced this using several burner numbers and each time, within seconds of logging in, the accounts are banned and the numbers blocked.  Using my own API ID/Hash, I can log in and successfully use the library as intended.

Can we remove the hard coded values in each of the examples and just point users to the correct location to generate their own?

**Comment by levlam** [comment]
There are a lot of factors which together can lead to account ban. Removing the hardcoded API ID can help someone, but some other users will be banned only if they will use their own API ID instead. By using burner numbers you act exactly like a spammer, so it's not surprising that the accounts was banned.

Currently, I want examples to be self-contained, so anyone can launch them without additional steps. But given that some innocent users are banned using examples, we definitely need to add an instruction to the examples on how the account can be restored in case of ban.

**Comment by YouTwitFace** [comment]
@levlam I can assure you that @MarcFreeman is not a spammer.

**Comment by MarcFreeman** [comment]
What about using official API information?  I just tried Android (ID 6) and I don’t get banned.  However, literally every number I’ve tried is being flagged.  It’s not an issue that the numbers are burners.  I first created the account successfully using TDesktop and everything was fine. It’s specifically THIS ID/Hash.

**Comment by levlam** [comment]
@YouTwitFace I haven't said that @MarcFreeman is a spammer, I've just said that creating new accounts using burner numbers and custom apps is exactly what spammers do, so chances to be blocked are much higher when doing this.

@MarcFreeman I don't want to go deep in details of how antispam system works, but I can ensure you that there are a lot of different factors, which can lead to or prevent an account ban. Most of users can safely use the examples with THIS ID/hash and some other users will not be able to use it with any API ID. Unfortunately, there are spammers, which use modified TDLib examples, so other users of the examples are more prone to ban. Removing the API ID will not help, because antispam system will just adapt and will be able to find and ban suspicious examples users anyway. So, the removal of API ID will just make example usage harder.
Usually antispam system is smart enough to not ban innocent accounts, but in the unlikely event of an innocent account ban the only thing we can do is to instruct users to write to recover@telegram.org for unbanning.

**Comment by YouTwitFace** [comment]
@levlam Why not remove the id and hash and put a link to https://my.telegram.org?

**Comment by levlam** [comment]
@YouTwitFace
1. "Currently, I want examples to be self-contained, so anyone can launch them without additional steps."
2. "Removing the API ID will not help, because antispam system will just adapt."

**Comment by YouTwitFace** [comment]
1. That's the problem
2. If you remove the id, there will be nothing to adapt to

**Comment by YouTwitFace** [comment]
Maybe leave a comment saying that there's a risk?

**Comment by levlam** [comment]
@YouTwitFace 
1. It's not a problem, it's a requirement.
2. Assumption that spammers could just use unique API ID to be never banned is definitely wrong. The chance of account being banned will stay pretty the same.

**Comment by zelenin** [comment]
@YouTwitFace this is not these specific api/id issue but common tdlib issue
https://github.com/tdlib/td/search?q=ban&type=Issues

**Comment by x2bool** [comment]
Hi! Can an account get a ban for just querying TDLib? I mean if account does not post or upload anything. I am getting some strange reports for my app.

**Comment by levlam** [comment]
@x2bool If it is logged in, then it is possible.

**Comment by x2bool** [comment]
@levlam Thanks for the quick reply. Is there a list of "do"s and "don't"s for TDLib? I mean you are probably not going to give out the details of your antispam system, but can we get some general description of things to avoid implying that the user is not spamming and in "read-only" mode. Because now i am super-confused about the reasons a user got banned, and I don't even know where to start looking.

**Comment by levlam** [comment]
Usually users are banned because they accounts looks like autoregistered, so the only "don't" is "don't register fake accounts". Some users can be wrongly classified as autoregistered bots, and their accounts are banned after that. In that case they just need to write to `recover@telegram.org`. Every official client asks users to write to that email, whenever they try to log in back, so all real users supposed to do that and to be restored soon after the accidental ban.

**Comment by x2bool** [comment]
Thanks. I'll ask him whether he registered a new account in my client. That would probably explain it.

**Comment by traderp** [comment]
I have the same problem. My account has been banned three times now, every time that I try using tdlib. I get a `USER_DEACTIVATED_BAN` error almost immediately and get disconnected from the Telegram app on my phone. I have a second account which works perfectly fine with the same `tdlib` code (which isn't posting anything, just observing channels). I'm running this code from a server on the clear (no Tor exit node). I wrote to `recover@telegram.org` every time and my account got re-activated in less than 24 hours, but no word from them. My account isn't fake or spam, it can easily be verified by email or sms. I would appreciate any tips from someone who struggled with the same issue.

**Comment by YouTwitFace** [comment]
@traderp if you're using the api id and hash from the example, try changing it.

**Comment by traderp** [comment]
I'm using my own api and hash.

**Comment by traderp** [comment]
This got squared away. Telegram finally replied to my email at `recover@telegram.org` and fixed the issue. I guess the solution is to be patient.

**Comment by levlam** [comment]
Since TDLib 1.5.0 if the account is banned by the server, TDLib will suggest through the log to contact `recover@telegram.org`. That's all that can be done on the TDLib's side.

**Comment by JohannYellow** [comment]
My story is similar to that of @traderp. I compiled the tdlib example application to test it out.  Initially I thought I'll just send messages between my number and my wife's number, so I got an api_key and hash with my account and logged in with her number on the example app and her number was banned immediately.  
Then I though maybe I shouldn't have used the api_key and hash from my account, so then I went out and got a dedicated mobile number (South African since that is where I live) and inserted it into an old unused phone.
I left the "test" api_key and hash unchanged and authenticated with this new number.  
It said "authorization is completed" but when I pressed [m] to send a message the number was banned again.
Note that there is not a single line of my own code running there - it is THEIR code that causes legitimite numbers to be banned immediately without any reason or explanation.
If they want to encourage 3rd parties to do development on tdlib why do they make it impossible for them to actually get it working!
If I'm going to write code based on tdlib that will be used on thousands of products I need more reliability and predictability than this.  The point is not that I can send an email and get it unbanned (which take days).  The point is I must know what do to not get banned.  
How can you consider a number spam if it only sends out messages to a few known contacts and only a few messages per day?  That's a stupid blocking algorithm you have there.  Can someone from tdlib please respond?
