### ISSUE TITLE
GetBasicGroupFullInfo: Group not found

### ISSUE THREAD

**Issue by jonua** [tdlib/td#563]
I execute the code
```
client.send(new TdApi.GetBasicGroupFullInfo(<id of my basic group>), new ChatResultsHandler());
```
and receive error:
```
Error {
  code = 6
  message = "Group not found"
}
```

ID of the group I retrieve by calling method *TdApi.GetChats*
what I'm doing wrong?

**Comment by levlam** [comment]
Probably, you pass a `chatId` instead of a `basicGroupId`. Another possibility is that you have called `getChats` and restarted the application after that. In that case you need to first load the group from `chatInfoDatabase` using `GetBasicGroup` method. It's hard to tell exactly, what's wrong, without exact requests.

**Comment by jonua** [comment]
@levlam hi, second described reason is true for me, thank you
