### ISSUE TITLE
What is the purpose of using underscore at the end of EVERY field?

### ISSUE THREAD

**Issue by Igorjan94** [tdlib/td#565]
Is_ it_ convenient_ to_ code_ this_ way_?

**Comment by levlam** [comment]
This is a most common way of naming class fields in С++, which is used to easily distinguish local variables and class members. Yes, it is a very convenient code style.

**Comment by Igorjan94** [comment]
I agree, that in your own class it can be convenient. But when I use library, I want to use normal names, not underscored. I know that it isn't local, cause it is used through dot or arrow and simply cannot be local

**Comment by levlam** [comment]
The only suitable alternative is to make all fields private and add trivial getters and setters instead. I doubt that this is a better alternative.

More over, there is no way we can just remove underscore in the all field names, because after that some names can coincide with C++ reserved words.

If you don't like C++ naming conventions, you can use TDLib from Java with lowerCamelCase field names, or C# with PascalCase filed names, or use JSON interface with ordinary snake_case names.

**Comment by Igorjan94** [comment]
Yes, getters/setters are even worse, of course. But when using normal colorscheme local variables and class member have different color and can be easily distinguished from each other without any prefixes/suffixes and other dirty stuff
