### ISSUE TITLE
Invite link field in supergroupFullInfo Class of a public super group is always empty

### ISSUE THREAD

**Issue by chairus** [tdlib/td#574]
Workflow:
 1. Invoke the `TdApi.SearchPublicChat`
 2. Invoke the `TdApi.GetSupergroup`
 3. Invoke the `TdApi.GetSupergroupFullInfo`

yet the `inviteLink` field is empty. Is there something I am missing?

**Comment by levlam** [comment]
In public supergroups users can be invited via link `https://t.me/<supergroup_username>`.

In private chats you need to have appropriate administartor rights to generte the link and call `generateChatInviteLink` first.

**Comment by chairus** [comment]
The group that I am interested in is public so there `inviteLink` field must be populated with `https://t.me/<supergroup_username>` but the field is empty when I get the response.

**Comment by levlam** [comment]
No, it shouldn't, because `https://t.me/<supergroup_username>` is not an invite link, it's a link to the chat. User can open the chat through it without actually joining. Additionally, chat administrators can create a real invite link even for public chats via `generateChatInviteLink`, which will be available in that field for them.

**Comment by chairus** [comment]
@levlam Thanks for clearing that up.
