### ISSUE TITLE
Java example [QUESTION]

### ISSUE THREAD

**Issue by chairus** [tdlib/td#583]
Are there any particular reason why in the Java example the team have decided to use the `CONSTRUCTOR` constant in checking the type of the `TdApi` object instead of using the method `instanceof`?

**Comment by levlam** [comment]
In my opinion, switch by `CONSTRUCTOR` is easier to read and maintain than a list of if/else when there can be a lot of possible classes as in implementation of `onAuthorizationStateUpdated` or `UpdatesHandler`. When there are only two possible classes like in all implementations of `Client.ResultHandler`, it would be better to use `instanceof` instead of switch.

**Comment by chairus** [comment]
Cool. So there really is not disadvantage using one over the other in term of the robustness of the code for example when there are new major updates of TdLib? Also is the `CONSTRUCTOR` value will likely to stay constant throughout the lifetime of TdLib?

**Comment by levlam** [comment]
`CONSTRUCTOR` and `instanceof` can be used to check the same property of an object, so code needs to be updated in the similar way regardless which of them is used

`CONSTRUCTOR` value is changed whenever the class is changed. Its numeric value should never be used directly.

**Comment by chairus** [comment]
Thanks @levlam
