### ISSUE TITLE
Getting updates

### ISSUE THREAD

**Issue by chairus** [tdlib/td#593]
Is there a way to forcefully make TDLib re-send the updates for a particular group/user/channel in case we miss the updates from those entities?

Thanks

**Comment by levlam** [comment]
@chairus There is no way to miss updates during ordinary workload, so what exactly do you mean by "miss the updates from those entities"? There is also no such thing as "missed updates", there is only current state, which is updated by updates.

**Comment by chairus** [comment]
@levlam What if say for example the user started the app and starts getting updates and before it can finish processing all the updates, for some reason, the app crashes, what would happen to the unprocessed updates? Will the app get them back again when I call the  client.receive() API? What would you suggest me do in this situation?

**Comment by levlam** [comment]
The user don't need all the updates since the beginning of time to get the current state and use the app. For example, `getChats` will always return current state of chat list and the app don't need to process all previous updates to get it. After restart updates will be sent only to update the current state.
So there can be two equally possible cases: TDLib will start from some old state and the updates will be delivered again to the app, or TDLib will start from the latest state and only new updates to the state will be sent to the app. If you are writing ordinary Telegram client app you need to do nothing, because user will always see the correct state.

If a group or a channel changed their username you usually don't receive update at all, because server can't send the update to all supergroup members. The `updateSupergroup` with the new username is sent only after some interaction with the supergroup happens, for example, a message from it is received. After the restart you are likely to receive only an `updateSupergroup` with the new username.
