### ISSUE TITLE
Abandoned? 

### ISSUE THREAD

**Issue by ForsakenHarmony** [tdlib/td#611]
There are like 0 commits in the last 3 months and telegram doesn't seem to actually care given that they don't use it

**Comment by RememberTheAir** [comment]
Commits are pushed all together when the next major release it's ready
> telegram doesn't seem to actually care given that they don't use it

Telegram X for Android and the new Telegram Web run on tdlib. The whole bot API runs on tdlib

**Comment by ForsakenHarmony** [comment]
> Commits are pushed all together when the next major release is ready

That's not how it works

Also telegram x is still not entirely official and the new Web version is not really mentioned anywhere?

Both being behind the current official apps where they push out new major feature updates

**Comment by RememberTheAir** [comment]
> That's not how it works

That's what tdlib devs are doing apparently. Changes are committed locally when they happen, and pushed all together when a new version is ready.

1.4's commits [have all been pushed the 30th of April](https://t.me/tgappsupdates/5587) despite being committed previously.

> Also telegram x is still not entirely official and the new Web version is not really mentioned anywhere?

Telegram X not being "entirely official" (it's still a product [marketed by Telegram as one of their apps thought](https://telegram.org/blog/telegram-x)) is not really relevant here as it has been used (and it's still being used) as a testing platform for tdlib in real life apps. The new web version is a react app using tdlib (tdweb): https://github.com/evgeny-nadymov/telegram-react

Anyway, if you look at the releases, a release takes more or less 5/6 months. The last release has been published on May 1, so I dont' see why you should think tdlib has been abandoned

**Comment by ForsakenHarmony** [comment]
Well, neglected at best

**Comment by isopen** [comment]
TDLib - gains momentum. Recently, there is support for unstable Dart.

**Comment by SmartManoj** [comment]
Is there any roadmap?

**Comment by levlam** [comment]
@SmartManoj There are no milestones, but if an issue is open it is supposed to be eventually closed, usually in the next stable release.

**Comment by levlam** [comment]
TDLib 1.5.0 was just released. See [Change Log](https://github.com/tdlib/td/blob/master/CHANGELOG.md) for the full list of changes.

**Comment by zelenin** [comment]
@levlam Use tags for release please, not comments in issues.

**Comment by isopen** [comment]
@levlam Keep commenting in the comments instead of tags. Otherwise, I will not see new changes.

**Comment by isopen** [comment]
@levlam Version 1.5.0 is the best at the current time. Particularly pleased with the changes in authorization and registration.

**Comment by levlam** [comment]
@zelenin The tag will be added when TDLib 1.5.0 will be actually released. For now only the source code was updated. There are a lot of things to update and check before the actual release.

**Comment by levlam** [comment]
@zelenin But you are right that I should have written "TDLib 1.5.0 source code was just released" instead.

**Comment by isopen** [comment]
@levlam Record Too Long. Better in the old way so that it’s clear that everything’s normal. Updated record too ...ЭTyped.

**Comment by isopen** [comment]
@RememberTheAir What do you think of TDLib version 1.5?

**Comment by isopen** [comment]
Because you are the most adequate of us. I agree with you that `TDLib 1.5` should be added to all `Telegram` clients. What do you think when this will be completed?

**Comment by RememberTheAir** [comment]
> Because you are the most adequate of us

Lol thank you, but I have a really opaque programming background and not the knowledge/experience to judge such a complex piece of code. I mean, I read the changelog and think "oh that's pretty cool, new stuffs" but that's pretty much it. I often lurk around here because I've been using Telegram for a few years now, I've seen more or less how it operates and I think I can express some of my opinions when Telegram's direction on something is pretty clear

> I agree with you that TDLib 1.5 should be added to all Telegram clients. What do you think when this will be completed?

Not anytime soon, for two reasons:
1. TDLib is still lacking some features and as the dev has pointed out on some issues in this repository, it will need some time before they can catch-up on the API. TDLib is not just a simple wrapper around the MTProto API, but implements some commodities and abstractions that required some work and we can't exclude, I think, this will happen again in the future with new stuffs
2. the three main clients (Telegram for Android/iOS and tdesktop) have reached a point where changing all the underlying storage/network implementation and replace it with TDLib would be too complex, time-expensive (Telegram would have to pause/delay their monthly updates schedule) and bugs-prone. So I think this is not going to happen at all, in my opinion. They might try to re-write some of them by launching some experimental client, like they're doing with Telegram Web. I think the main candidate for this is tdesktop, since it lacks local storage and Preston said a couple of times the app's code is really complex at this point and it would be nice to refactor the whole thing. Idk if they're planning to do it (I don't think so), but surely if I had to bet on an app, I would bet on tdesktop

**Comment by levlam** [comment]
@zelenin Now after everything was checked and all documentation was updated TDLib 1.5.0 is actually released: https://github.com/tdlib/td/releases/tag/v1.5.0.
