### ISSUE TITLE
java example cyrillic issue

### ISSUE THREAD

**Issue by kalian** [tdlib/td#618]
#520 was vary halpful for my country, but why official telegram client works fine without proxies ...... i'm from russia......but main question is below:
after authorization (parameters.systemLanguageCode = "ru";) in java console i`ve wrote "sm 825663194 кириллица" but message was generated with   
content = MessageText {
    text = FormattedText {
      text = ":8@8;;8F0"
      entities = Array[0] {
      }
and reccived message is not "кириллица" but ":8@8;;8F0"
chat names with cyrillic simbols looks fine
how may i fix it?

**Comment by kalian** [comment]
#520 was vary halpful for my country, but why official telegram client works fine without proxies ...... i`m from russia

**Comment by levlam** [comment]
The problem is very likely to be in the way symbols are read from the console and not in the TDLib itself. You need to check that in the console settings an encoding which is able to represent cyrillic symbols is chosen. You also need to check that Charset.defaultCharset() is the same encoding that is used in the console and if it isn't then pass explicitly correct Charset to InputStreamReader.

Could you specify, which exactly console application is used and its encoding, and which charset is default on your system?

**Comment by kalian** [comment]
thanks a lot!! i have added to "netbeans_default_options"  "-J-Dfile.encoding=UTF-8" in my netbeans config file.
