### ISSUE TITLE
[Missing] Animated Stickers

### ISSUE THREAD

**Issue by Sajilck** [tdlib/td#624]
Blog: https://telegram.org/blog/animated-stickers

**Comment by levlam** [comment]
Animated stickers support was added in TDLib 1.5.0. See [Change Log](https://github.com/tdlib/td/blob/master/CHANGELOG.md) for the full list of changes.

**Comment by RememberTheAir** [comment]
Btw animated stickers support doesn't look completed yet, at least according to the docs. [`InputSticker`](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1input_sticker.html) is still described to require a PNG file (but maybe it's just the docs being outdated, which is more likely since I doubt the API would refuse a `.tgs` file as `InputDocument`). In the same way, the bot API apparently still wants png files only for [`addStickerToSet`](https://core.telegram.org/bots/api#addstickertoset) and in a similar way there's no way of creating an animated pack using [`createNewStickerSet`](https://core.telegram.org/bots/api#createnewstickerset) (which appear to miss a similar functionality in raw tdlib too, see [create_new_sticker_set](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1create_new_sticker_set.html))

**Comment by levlam** [comment]
@RememberTheAir Creation of animated sticker sets by bots is not supported server-side yet.

**Comment by RememberTheAir** [comment]
@levlam oh, I see. Thank you
