### ISSUE TITLE
where is "Bot api getChatMembersCount" method in tdlib?

### ISSUE THREAD

**Issue by smaznet** [tdlib/td#640]
Hi i need group realtime members count and `getSupergroup` sometimes returns 0 or wrong members count but Bot api method works correctly

**whats alternative of `getChatMembersCount` in Tdlib?**

**Comment by levlam** [comment]
This is a clearly documented behavior:
```
@member_count Member count; 0 if unknown. Currently it is guaranteed to be known only if the supergroup or channel was found through SearchPublicChats
```

The actual member count of a supergroup is available in `supergroupFullInfo` and can be retrieved using `getSupergroupFullInfo` method.

**Comment by smaznet** [comment]
SearchPublicChats?

I used SearchPublicChat but my account limited for about 2000 seconds

What's SearchPublicChats do?

**Comment by levlam** [comment]
This is also expected, because every method has limits on its usage frequency, which normal users never exceeds. `SearchPublicChats` is for searching public chats, not for getting their member count.

You can use `GetSupergroupFullInfo` to get supergroup member count, but you will be flood limited anyway.

**Comment by smaznet** [comment]
Ok thank you 
so i use Bot Api for this

But I think TDLib on bot api is different from this TDLib

**Comment by levlam** [comment]
No, it is exactly the same.
