### ISSUE TITLE
Cannot determine chat id from push notification data

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#649]
We are using the Ubuntu Touch push gateway with `deviceTokenUbuntuPush` as a parameter for registration. That works still fine, and we get the notifications on the gateway. However, I discussed changed behaviour with Igor Z. a few times:

- Push notification JSOns do not carry the same information for all dialogs, chats or supergroups/channels, especially number of unread messages in that chat
- We do not receive an empty message anymore to clear notifications when reading on the device. Reading on another device triggers them still.
- The chat id for tdlib needs to be determined with this hack:

``` 
if (custom.keys().contains("from_id")) {
        tag = custom["from_id"].toString();
        chatId = tag.toLong();
    } else if (custom.keys().contains("chat_id")) {
        tag = custom["chat_id"].toString();
        chatId = tag.toLong() * -1;
    } else if (custom.keys().contains("channel_id")) {
        tag = custom["channel_id"].toString();
        chatId = (tag.toLong() + 1000000000000) * -1;
    }
``` 
We cannot use tdlib´s notification functions so far, as Ubuntu Touch suspends all apps in the background with SIGSTOP. So at the time the notifications arrive, we need to utilize an external helper. Same problem as with the avatar pictures I asked about some days ago.
This hack is not stable, I know. Is there any better way to determine the chat ID from the server id?

**Comment by levlam** [comment]
No, there is no better way, because this is exactly, what is done by TDLib to get unique chat_id. You can find actual conversion code in [DialogId::get_peer_id](https://github.com/tdlib/td/blob/master/td/telegram/DialogId.cpp#L113), but this conversion is a simplest of the problems and there are really a lot of other pitfails in notifications implementation.

We came to conclusion that application has no enough data to reliablу support push notifications without a lot of data stored in TDLib. For example, a push notification can come after the message was read, or deleted, or edited and application can't know that without launching TDLib. So, the best way to process a push notification in external helper is
1) obtain exclusive lock on TDLib's instance using some shared memory;
2) if successfully locked, launch TDLib, process the push notification, close TDLib;
3) if failed to lock, because main application is run, then ask it to process the push notification;

If communication between external helper and main app processes is not possible even via shared memory, then you can blindly launch TDLib, process the push notification if succeeded, close TDLib. If that fails, then the main application is run now, so the notification will be shown anyway after received from the server.

**Comment by Flohack74** [comment]
One more comment, does tdlib lock reliably on the db and will return an error code when we would launch it a 2nd time?

**Comment by levlam** [comment]
Yes. The database is properly locked since ever for opening twice from different processes and since TDLib 1.4.0 for opening twice from the same process. Currently, it tries to wait for at most 10 seconds before it gives up to lock the database and returns an error for `setTdlibParameters` to the caller. If you want to reduce this time, you need to change constant `100` proportionally [here](https://github.com/tdlib/td/blob/21dee3b1d923f3fdacc711b46ad102b1d0d1439b/tddb/td/db/binlog/Binlog.cpp#L175) to a smaller value.
