### ISSUE TITLE
TDLib is always catching up in terms of features, no feature parity with official clients

### ISSUE THREAD

**Issue by Kenya-West** [tdlib/td#662]
This is the main issue for TDLib - it is always missing features when official client  gets them first.

I understand there is some time taken to implement all the features, test them and roll out to library, but 3rd party developers have to wait for months to get certain APIs. It makes 3rd party apps less functional and therefore it moves part of their user base to official apps.

For example, I as a user had to wait native polls in Unigram for two months before they finally arrived.

Can maintainers answer: what is the problem to deliver APIs for features (revealed in official clients) faster?

**Comment by levlam** [comment]
In the second part of the last year we spent some time implementing a lot of big features, which was already available in other clients or are TDLib specific. For example, TDLib has received:
- Full support for push notifications handling and Notification API;
- Full support for language packs;
- Full support for media streaming;
- Getting Started guide and list of TDLib's usage examples;
- TDLib build instructions generator;
- Support for building on low-memory devices;
- Methods needed to use TDLib remotely without restrictions by any number of clients;
- Advanced logging API;
- Official browsers support;
- A lot of bot-specific features.

You can see in the [Change Log](https://github.com/tdlib/td/blob/master/CHANGELOG.md) that TDLib has received even more features than other official clients.

In general, TDLib is supposed to support new features at the same time as official clients and release a public version with them few weeks after official application release. The gap in a few weeks is unavoidable, because TDLib needs
- Full documentation for the changes;
- Stable finalized API, which is easy to use;
- To be tested on all supported platform, list of which is much longer than for all other official applications all together, with all supported compilers and dependencies versions;
- To be thoroughly tested before release, because unlike official application we can't force updating of all TDLib-based clients;

Currently, TDLib lags behind official clients approximately for three months instead of two weeks, but I hope that TDLib will catch them till the end of the year.

**Comment by mrkiko** [comment]
thank you very very much for all your work guys.

**Comment by levlam** [comment]
TDLib source code was updated today with support for all the latest features of official clients. As I said in the previous message, TDLib catched other official clients in terms of features before the end of the year. Stable TDLib 1.6.0 release with updated documentation and finalized API is expected in a few weeks.
