### ISSUE TITLE
Voice note Thumbnail is not transparent

### ISSUE THREAD

**Issue by nanu-c** [tdlib/td#664]
This looks ugly on everything, that is not white, can you change it to a png/webp?
![grafik](https://user-images.githubusercontent.com/404058/62826676-c8970980-bbbf-11e9-8d5e-6b8b2cdd4a89.png)

**Comment by levlam** [comment]
No, voice notes thumbnails can be only in JPEG format. This depends on the server and can't be changed client-side.

**Comment by nanu-c** [comment]
I know, that this depends on the server, but on official telegram apps you also have a transparent background. I think, the problem here is, that official tg doesn't use the thumbnail for voice notes so it doesn't mater, whether the display is  correct or not. Should I open a issue on the server?

**Comment by levlam** [comment]
Thumbnails format is very unlikely to be changed, because thumbnails are generated automatically and needs to be shown on an arbitrary background. Thumbnails with transparency will generally look much uglier on a random background then thumbnails without transparency. There are also a lot of other reasons to stick with JPEG.

**Comment by nanu-c** [comment]
Okey, then we try to find another solution for nightmode on ubuntu touch
