### ISSUE TITLE
How to set AuthenticationCodeType to AuthenticationCodeTypeSms ?

### ISSUE THREAD

**Issue by huang-ju** [tdlib/td#676]
How to set AuthenticationCodeType to AuthenticationCodeTypeSms ?

**Comment by huang-ju** [comment]
I want code to be sent via SMS

**Comment by chairus** [comment]
@huang-ju When you receive an `authorizationStateWaitCode` response it will contain a `code_info_` property which tells you how the authorization code was sent, i.e. via Telegram message or SMS, the code will usually be sent through via Telegram message first, in order to send it via SMS you would have to call the `resendAuthenticationCode` but this will only work if current authorization state is `authorizationStateWaitCode` and the `next_type_` property of `authorizationStateWaitCode` class is `authenticationCodeTypeSms`.

Hope that helps

**Comment by huang-ju** [comment]
@chairus  How do I set the nextType to AuthenticationCodeTypeSms ?

**Comment by levlam** [comment]
@huang-ju There is no way to do that.

**Comment by huang-ju** [comment]
![image](https://user-images.githubusercontent.com/46550127/63670216-b0092f00-c80e-11e9-82c5-2a460887e63b.png)

@levlam  Why can clients send SMS?

**Comment by levlam** [comment]
@huang-ju See absolutely correct [answer](https://github.com/tdlib/td/issues/676#issuecomment-524621228) of @chairus again. That's all that clients can do.
