### ISSUE TITLE
messageSendingStatePending message id

### ISSUE THREAD

**Issue by mib32** [tdlib/td#700]
When I send the message - I receive back the Message object with state `messageSendingStatePending` and Id, if after some time I will try to use this Id to get the message - I will receive 404 Not Found error. The message gets new ID after it sent. Is it supposed to be like that? 
For example, I'd like to send the message and after that be able to edit this message, but this is making it much harder.

**Comment by levlam** [comment]
Yes, it is supposed to be exactly like that, otherwise it would be impossible to see sent messages in chat history before they are actually sent. This would make applications unusable without active and good network connection. See https://github.com/tdlib/td/issues/511#issuecomment-473559662 for more details.
