### ISSUE TITLE
Usable JSON API description/schema

### ISSUE THREAD

**Issue by dancojocaru2000** [tdlib/td#735]
At the moment, we only really have the `.tl` file, which is pretty unusable. It's complicated to read and one can't really figure out where to start parsing it to generate useful data structures in other programming languages. 

What we would need is something like [JSON Schema](https://json-schema.org), which we can afterwards use to generate data structures in many other languages. That schema should also specify if values are optional or not. (example: in `tdlibParameters`, `application_version` is required but we have to rely on the documentation to tell us that; a schema would automatically tell us what's needed and what's optional).

It's nice that we have the C JSON API, but it feels like we're left manually writing JSON strings and concatenating data rather than interacting with structs and functions in there language we're coding in.

**Comment by levlam** [comment]
.tl scheme is perfect for manual editing and for automatic parsing. It can be easily used to generate anything you want.

Your example about `application_version` is wrong, because any parameter in requests can be omitted, but then the request may become logically invalid. You can't just mark some parameters as optional or mandatory, because it would be wrong. The things are much complicated, so generally speaking you need to specify all parameters, unless empty value is what you want to specify. This doesn't mean that the parameter is optional, it is still required, but we allow to not specify null/false/0/'' parameters.

You can find in [example list](https://github.com/tdlib/td/blob/master/example/README.md) a lot of TDLib wrappers and bindings in various programming languages with automatically generated classes and methods, all of which are generated from .tl scheme. It is very non-productive to manually generate JSON objects all the time. Between what programming language do you use?

**Comment by dancojocaru2000** [comment]
I'm not exactly sure I get your point. If omitting a parameter renders the request logically invalid, then that parameter is required. In my case, that would be `application_version`, as the documentation specifies: _"must be non-empty"_. Meanwhile, something like `use_test_dc` is not required, it has a default value that is valid if the parameter is left out. That makes it an optional parameter. If we are happy with the default, we don't have to specify it.

I have yet to find how exactly one should parse the .tl schema to generate data structures (and the first lines of it are especially confusing). I did not notice the examples page that you pointed out before and that would be my fault. I will check it out to see.

**Comment by levlam** [comment]
`use_test_dc` is also required, because you must specify which environment you want to use. But in JSON interface if it is not specified we will assume that you passed `false`. If the parameter would be called `use_production_dc` the situation would be the same, but the behavior if the parameter is not specified would be the opposite. TDLib's methods have no optional parameters, they just allows in JSON interface to not pass some parameters. I don't call this automatical treating of missed parameters as having `null/false/0/'` value `optional parameters`, because all parameters are optional in that sense and most method has much more sofiscated restrictions than plain "this parameter is required". For example, you can't send an empty message, but you can't also send a message with text containing only spaces, or when sending a photo you must specify a caption, but the caption can be empty, which is perfectly valid.

So all parameters have default value, but that doesn't mean that they are optional. Behavior of these default values is more like behavior of function arguments in Javascript where you can call any function with any number of arguments without restrictions and non-passed arguments just have a pre-defined value.

Ignore the first lines of .tl scheme. They just describe built-in types to make rest of the file a valid TL-scheme for the original TL-parser. We deliberately use only very-very basic TL features in td_api,tl to make its parsing as simple as possible.

**Comment by dancojocaru2000** [comment]
In coding, some methods also have more advanced conditions. Regardless, we can say that, in the following C++ function, `b` is an optional parameter because you can just omit it and it assumes it's default value.
```cpp
int example(int a, std::string b = "") { ... }

example(1, "test"); // valid
example(2); // also valid, b is optional
example(); // invalid, a is not optional
```

Maybe `example` requires that `b` is either empty or contains at least 2 chars, and that can only be specified in the documentation and at runtime, but by defining the method like so, we have a guarantee that we can omit `b` and the method will still be valid. We also need to specify `a` or the function call will fail before we even get to runtime.

**Comment by dancojocaru2000** [comment]
It doesn't. However, I'm talking about the JSON interface, from which you can omit some parameters, defaults being assumed. It was said above that you can omit all of them, but some are required to be changed, therefore not omitted, so there can be a clear distinction between required and optional parameters.

**Comment by puppy0cam** [comment]
If a missing field can cause a request to be invalid, then why does the JSON interface coerce the value into a zero-like value instead of throw? If you want to proceed with a request that is missing parameters, it would be more correct to explicitly declare the parameter as a zero-like value instead of just assuming it is. Data received from tdlib does this, and it should be expected that data sent to tdlib does the same.

**Comment by levlam** [comment]
@puppy0cam Because the error will be returned anyway if the combination of all parameters is invalid. Checking parameters in every interface is like a client-side check against server-side check. More over it could cover in the best case near 10% of all checks.

All parameters are required in TDLib requests, i.e. if a method has a parameter `system_version` then the application must provide a correct `system_version`, not a some random non-empty string. See for example, https://github.com/tdlib/td/issues/521 or https://github.com/tdlib/td/issues/738 both of which happenned because of wrongly specified `system_version`.

We could easily throw an error in JSON interface if a field is missing, but we preferred convenience over strictness. You can easily change that behavior and make all fields required by changing in the line
https://github.com/tdlib/td/blob/a2429d595ce38456240717219fe4e61c3ba8b38a/td/generate/tl_json_converter.cpp#L100
`true` to `false`.

**Comment by dancojocaru2000** [comment]
Some fields make total sense to be optional. For example, `enable_secret_chats` can safely default to false is omitted, which is what happens. Considering tdlib emulates optional parameters by default, it should embrace it by providing some kind of type definitions that specify which arguments make sense to be left out and which are required. I especially argue that this is the case since the documentation for `tdlibParameters.application_version` specifies that it should not be empty. If the documentation needs to specify thing and if the server returns an error if omitted, some type definitions should exist to highlight that this parameter is indeed needed.

**Comment by levlam** [comment]
@dancojocaru2000 But `enable_secret_chats` and `use_*_database` should be `true` by default for a general application, because usually there are no reasons to disable them. They must be deliberately specified to be `true` or `false` by the application, so even TDLib had optional parameters, only `tdlibParameters.enable_storage_optimizer` and `tdlibParameters.ignore_file_names` could be marked as optional.

I don't claim that TDLib doesn't have parameters which can be marked as optional. For example, `sendMessage.reply_to_message_id` or `searchChatMessages.sender_user_id` are in fact optional parameters. But anyway there is no way to have classes with optional class fields in statically typed languages like C++, Java or C#, so we never specify a parameter as optional and deliberately say that all parameters are required.

Documentation of `tdlibParameters.application_version` contains "must be non-empty" clause, because it is a very common mistake to pass there an empty string. But simple "non-empty" is also wrong for this parameter, because the exact application version needs to be specified, preferably in the `X.Y.Z...` format. There is no guarantee that the server will not reject versions in other formats in the future.

> some type definitions should exist to highlight that this parameter is indeed needed.
This is default behavior applied to all parameters. All of the parameters are needed and are very important. I gave in the previous comment examples of issues which already happened because applications specified non-empty, but incorrect ` tdlibParameters.system_version`.

Optional parameters can be specified in TL-scheme as `reply_to_message_id:flags.0?int53`. You can find a lot of such fields in the [Telegram API scheme](https://github.com/tdlib/td/blob/a2429d595ce38456240717219fe4e61c3ba8b38a/td/generate/scheme/telegram_api.tl#L898), but TDLib API deliberately doesn't use them for simplicity.

**Comment by dancojocaru2000** [comment]
In Java and C#, there are nullable types. C# 8 added support for nullability annotation. New language like Rust have Option<T> type. Also, default parameters are easily implemented in constructors. `enable_secret_chats` makes sense to be disabled by default and only enabled if explicitly specified. I get the overall point that it's best practice that all parameters should be specified, but, considering how the API itself behaves, it just feels a bit odd.

**Comment by levlam** [comment]
@dancojocaru2000

>In Java and C#, there are nullable types. C# 8 added support for nullability annotation.

Nullable annotation still can't be applied to fields of scalar types, so this support is useless for `sendMessage.reply_to_message_id`, `searchChatMessages.sender_user_id` and most of other fields. In fact, we use Nullable annotation in our native Java bindings and use null instead of some objects, but only in the objects are sent from TDLib to applications.

> New language like Rust have Option type. 

C++ has `std::optional` and such type can be easily introduced in other programming languages, but `Option` type has a big memory and performane overhead and it is very cumbersome in usage without built-in language support, which none of C++, C# or Java have, so this is also not an option. 

> Also, default parameters are easily implemented in constructors.

Java has no optional parameters even in constructors. Constructors in most programming languages also are restricted to have optional parameters only in the end of the list, so this would require reordering of a lot of fields. Optional parameters also are very dangerous when a new non-optional parameter needs to be added,

Giving all of this all parameters in TDLib API requests was specified as required. But taking in account nature of JavaScript we allowed to not always specify a field's value in JSON API. For most other programming languages we expect that wrappers would generate strongly typed native classes for TDLib API classes and will automatically serialize them to JSON including all needed fields.

**Comment by dancojocaru2000** [comment]
I get that languages that weren't designed for such things (e.g. C++) have a tough time implementing optional parameters and for those languages, by all means, just ignore optionality and make everything required. But the type definitions should be flexible and say something like "this works if you leave it out, your choice if you actually will or still keep it required".

**Comment by dancojocaru2000** [comment]
Whoops, accidentally closed the issue, but I get the overall point. Also, I still think that `.tl` is quite hard to read and something like JSON Schema would have been better. For example, I don't understand the following (sketched, I'm on mobile phone so can't look up a real example atm):
```
something = SomeType;
somethingElse = SomeType;
```
I don't get why two things can have the same thing after equal and I can't easily find some documentation explaining it.

**Comment by levlam** [comment]
@dancojocaru2000

The TL subset used for TDLib API is very simple.
A simple object declaration
```
error code:int32 message:string = Error;
```
describes a type with its fields. The type name here is `error` and it is inherited from an abstract type `Error`.

Some abstract types can have more than one inheritor. For example, in
```
textParseModeMarkdown = TextParseMode;
textParseModeHTML = TextParseMode;
```
described that type `TextParseMode` can be one of `textParseModeMarkdown` or `textParseModeHTML`. Abstract class names always begins with a capital letter and ordinary classes always begins with a lowercase letter.

There is also a `---functions---` section, which describes all TDLib API methods. Declarations there are different only in one thing: they contain method's result type after `=` instead of the inherited abstract class. For example, the method
```
parseTextEntities text:string parse_mode:TextParseMode = FormattedText;
```
has string argument `text`, the argument `parameters` of an abstract type `TextParseMode` and returns an object of type `FormattedText`. The latter is an abstract type with one constructor `formattedText`, so the result always will be of the type `formattedText`.

That's all. But we didn't expect that even this needs to be known and have auto-generated documentation for C++, Java and C# interfaces. There are a lot of third-party wrappers which also provide auto-generated documentation in a usual form for other programming languages.

**Comment by dancojocaru2000** [comment]
Holy heck, this is so helpful! Thanks!
How about the first part with something like `boolTrue = Bool`?

**Comment by levlam** [comment]
You can safely ignore first 12 lines of the scheme. They just describe built-in types `double`, `string`, `int32`, `int53`, `int64`, `bytes`, `bool` and `vector` and are presented only to make the scheme a valid ordinary TL-scheme. For example, before we can define `error code:int32 message:string = Error;` we must define somehow types `int32` and `string`.
