### ISSUE TITLE
call getChats multiple times returns no result

### ISSUE THREAD

**Issue by MalteToenjes** [tdlib/td#751]
Isn't it possible to call the function getChats times  in a row? When I call it the 2nd time I don't get any results...

**Comment by levlam** [comment]
There is no reason to call `getChats` twice simultaneously, because you can't provide correct `offset_order` and `offset_chat_id` to the second request. But you must call `getChats` multiple times with adjusted `offest_order` if you need more chats that can be returned in a single response. See also https://core.telegram.org/tdlib/getting-started#getting-the-list-of-chats.

**Comment by MalteToenjes** [comment]
To clarify, I have to listen to _updateNewChat_ to get the right response ye? Because when I call getChats _chat.order_ is always 0. Also I only get around 15 callbacks with _updateNewChat_ even if I set the limit to 100 or higher...

**Comment by levlam** [comment]
`Chat.order` is updated by various updates. See [Java example](https://github.com/tdlib/td/blob/9293f07464276d58974164e41a4bb57d3362a258/example/java/org/drinkless/tdlib/example/Example.java#L235) for the full example of chat list loading.

**Comment by MarioSaldanhaLobo** [comment]
What updates exactly should we expect to receive when calling getChats the first time? (assuming I have chats, of course)

Using:
offsetOrder = Long.MAX_VALUE;
offsetChatId = 0;
ChatList = new TdApi.ChatListMain();

**Comment by levlam** [comment]
@MarioSaldanhaLobo You should expect any update any time. If you process all the updates, after `getChat` request is finished, you should know the position of more chats than previously.

**Comment by MarioSaldanhaLobo** [comment]
@levlam, My question was on "laboratory" scenario where only the updates related to my request would arrive.
So... I need to handle every Chat-related update. There is no single update that contains all the information (limited to the traditional 100 or 50 like when requesting GetChatHistory).
Correct?

That's what I've been doing. But I thought there would be a more direct way - to really get a list (or the top part of it).

**Comment by levlam** [comment]
@MarioSaldanhaLobo There is no way to differentiate "the updates related to my request" from other updates even theoretically. 

The chat list changes all the time. Whatever the `getChats` method returns, you can't use its result reliably, because a lot of time has passed between request start and response return. During this time messages in some previously known chats was deleted and they has been moved down. Such previously known chats will be returned again by `getChats`. Some chats received new messages and has been moved up, so they will never be returned by consecutive `getChats` calls. And these actions aren't related in any way to `getChats` calls.

**Comment by MarioSaldanhaLobo** [comment]
@levlam , thanks.
