### ISSUE TITLE
Multiple and parallel Downloads

### ISSUE THREAD

**Issue by daparici** [tdlib/td#786]
Is there any way to have several media files downlading simultaneously?. It seems to download only one file a time, even setting different priorities.

**Comment by levlam** [comment]
TDLIb downloads files in the fastest possible way. If multiple files can be downloaded in parallel because there are enough free network capacity, then they will be downloaded in parallel. But it is much better to have some files fully downloaded then have all files partly downloaded, so files with the same priority are downloaded in the reverse order of `downloadFile` requests. This ordering doesn't affect total download time in any way, downloading recently requested files first.
