### ISSUE TITLE
add support for hooking into the logging framework

### ISSUE THREAD

**Issue by mgrandi** [tdlib/td#794]
It seems that the only methods an application can call to impact the logging of `tdlib` is `setLogVerbosityLevel ` and `setLogStream `, in which `setLogStream` only lets us set it to be `default` (stderr or syslog), `off` or `file`

I"m interested in intercepting the `tdlib` log statements using the programming language i am using , and therefore managing it using the logging framework of the language using `tdlib`. 

perhaps have it set so we can set the log stream to be 'event' and then logging events can get sent via the normal mechanism and therefore intercepted using `td_json_client_receive`?

It would be nice to get all events in whatever mechanism gets decided upon, since it seems that `tdlib` starts immediately logging when `td_json_client_create()` is called, and the wrapping application might lose some events between when `td_json_client_create()` is called and when they call `td_json_client_send()` with the parameters to call `setLogStream`

**Comment by levlam** [comment]
This is not possible, because all log methods are synchronous and can be called without any TDLib instance. The log stream is shared among all active TDLib instance and the log is active even there is no TDLib instance at all.

Additionally, the TDLib's log is not supposed to be used for automatic processing. You can always redirect the log to a file and read the file, but whatever problem you are trying to solve with the log processing, you would better find another way to solve it.

**Comment by mgrandi** [comment]
its not that i want to process it, i just want it be forwarded to the python logging module so it acts like any other log message in python, and i can turn it on /off, have it forwarded to a file, etc

**Comment by levlam** [comment]
@mgrandi That's a valid goal. Currently, we support only reverse way to use TDLib's log as a primary logging system via the method `addLogMessage`.

The main problem is that such log hooking can be done only via callback in the same way as td_set_log_fatal_error_callback works. There are a lot of programming languages in which it is impossible to create a callback, which can be called from the native code, but fortunately Python is not one of them, so a similar approach should work for it.

**Comment by mgrandi** [comment]
are you saying that such a 'hook' exists now? or if one were to be created, because i only see these methods exported by tdjson.dll:

```
td_json_client_create
td_json_client_destroy
td_json_client_execute
td_json_client_receive
td_json_client_send
td_set_log_fatal_error_callback
td_set_log_file_path
td_set_log_max_file_size
td_set_log_verbosity_level
```

**Comment by levlam** [comment]
td_set_log_fatal_error_callback is almost needed hook, but it is called only on fatal logging lines (with verbosity level -1). And it is called additionally to ordinary logging, not instead it.

**Comment by exikyut** [comment]
A Linux-specific hack could be to use a `path` of `/dev/self/fd/N`, where N is the writer end of a `pipe()`. I have minimally tested this and it seems to work.

The only issue with this approach is that it is not possible to disable file rotation when it reaches `max_file_size`, which is [counted internally](https://github.com/tdlib/td/blob/9964d24ec8e03bd0bc4d5fe33438f056d133fc1a/tdutils/td/utils/FileLog.cpp#L72). Furthermore failure of the `rename(..., ... + '.old')` call is considered fatal. So, you would currently need to call `setLogStream` periodically to reset the internal counter. The function does not actually switch files (close old, open new) unless you pass a different path, but I \**think*\* (from reading `Logging::set_current_stream` and `FileLog::init()`) that the rotate threshold does get reset if you pass in the same path with a different `max_file_size`.

Possibly somewhat understandably, for now I'm just using real files while I tinker/experiment with tdlib :) but this method seems stable... albeit somewhat inelegant.

I think that using pipes/socketpairs/similar could be an interesting and viable approach, with the main (only?) caveat that the reader must ensure it keeps up with incoming log messages so that tdlib does not block, which may (considering extreme edge cases) at least cause difficult-to-reproduce states (not necessarily bugs) in different threads.

On tdlib's side, this would (to me) look like making file rotation disable-able (potentially by setting `max_file_size` to `-1`), possibly providing basic references to how to manage pipes on different platforms (for example, I have no idea if what I'm describing is even viable on Windows), and making note of the above caveat (likely among other gotchas).

It's possible this approach may be unworkable for reasons I haven't thought of.

**Comment by levlam** [comment]
> The only issue with this approach is that it is not possible to disable file rotation when it reaches max_file_size,

You can specify `max_file_size` to be `2^63-1`, which will be never reached.

**Comment by levlam** [comment]
The function `td_set_log_message_callback` was added to TDLib 1.7.5, which allows to intercept all TDLib log entries. Combined with `logStreamEmpty` it allows to completely redirect TDLib's log anywhere.

**Comment by mgrandi** [comment]
thanks! not sure if you added that in response to this bug ticket but this helps quite a lot! :)

**Comment by levlam** [comment]
@mgrandi You was the first to point out that such function is needed, so the change was done thanks to this issue. Thank you for bringing it up and sorry that adding the function took so long.
