### ISSUE TITLE
Question: Notification workflow for tdlib vs. classic Telegram

### ISSUE THREAD

**Issue by Flohack74** [tdlib/td#799]
Hi,

I just read in the Android app about the KeepAlive service used to restart the App so "notifications can be received" - so basically do you no longer use GCM or similar services for pushing notifications to the official apps? I also noticed that I can receive notifications on a plain LineageOS installation wiht no GApps etc.

**Comment by levlam** [comment]
KeepAlive service was required for Android 2.* and Android 4.*, because GCM was very unreliable there. It should be disabled by default now from Android 6.0 because of doze and other restrictions on apps work in background. So now FCM is a primary source for notifications on Android.

TDLib keeps background connection unless NetworkType is set to `networkTypeNone`. In that case most notifications will be received through that background connection.

**Comment by Flohack74** [comment]
Ah ok, so Telegram and Telegram X will still use FCM but not always. So suppose our tdlib client is active, connected, and new notifications arrive, we would need to react on the notification from tdlib. Can you do me one favor, there is the push type "Ubuntu Touch", can you check if this still triggers *always* or only when the client is not reachable via tdlib? We need to start thinking about migration scenario for Ubuntu Touch push services to the new format.

**Comment by levlam** [comment]
Pushes are sent always for messages in unmuted chats. They can only be delayed for approximately 3o seconds if the user is online from some other client.

**Comment by Flohack74** [comment]
Ok fine. Regarding changes to the push message format: Last time I did this together with Igor Z., is he still in charge of that? We need to fix the json content that is currently sent to our servers, but it must be done carfeull ynot to disrupt existing push notifications.

**Comment by levlam** [comment]
@Flohack74 Yes.
