### ISSUE TITLE
TdApi.java - MessageChatDeleteHistory content missing

### ISSUE THREAD

**Issue by jojo27888** [tdlib/td#816]
After compiled tdlib for java, the generated TdAPI.java doesn't contains MessageChatDeleteHistory class.

I tried to clear history of a chat in Telegram App and then call the function GetChatHistory that returns no messages, not even a message with content MessageChatDeleteHistory (that seems to exists in this repository) saying that history was cleared.

Is it a way to add this support by myself ?

Thanks for the help

**Comment by levlam** [comment]
Because there is no such an object and a message content in TDLib API.

MessageChatDeleteHistory is not a real message. It even not always means that the history was cleared. It is just a marker that the chat should be kept in the chat list. It is handled internally by TDLib and never treated as a real message. There is no way such a message can be received by an app from TDLib and there is no reason to return in to the app either.

**Comment by jojo27888** [comment]
ok, thanks for the answer.

It would have been interesting for a user to know that the history of a chat was cleared by himself or his correspodent and also when it was cleared...

For example, the correspondent go into the chat and see that there is no message anymore (indeed, the other user has cleared the history but he doesn't know it), he will maybe thinking that there is a bug in the app because all the messages of this chat disapears.

Is it a way to know this with TDLib ?

**Comment by levlam** [comment]
No, there is no way to know this with TDLib.

The history is often cleared without keeping a MessageChatDeleteHistory message with complete removal of the chat from the chat list, so there is no way to reliably get this information at all. Clients show "History was cleared" only in the chat list if there are no messages and a draft in the chat.

**Comment by jojo27888** [comment]
ok, thanks for all these information.

Regards
