### ISSUE TITLE
Adding a user to a group using method `AddChatMember` results in an error

### ISSUE THREAD

**Issue by jonua** [tdlib/td#819]
Hi,
I'm trying to add user to basic group using method [AddChatMember](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1add_chat_member.html) and I receives message log:

> error=3, Chat is deactivated

this behaviour are declared [here](https://github.com/tdlib/td/blob/master/td/telegram/ContactsManager.cpp#L4304)

In [documentation](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1basic_group.html) for a basic group I see:

> bool | is_active - True, if the group is active.

I don't understand, how to set is_active=true for group?

And second question: in [the docs for addChatMember Class Reference](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1add_chat_member.html) I see

> Members will not be added until the chat state has been synchronized with the server.

What is mean - "synchronized with the server"? How it works? What should I do?

**Comment by levlam** [comment]
Deactivated basic group can't be used to send new messages, nor add new members. It is not possible to activate it after deactivation either. Currently, the only way to deactivate a group is to upgrade it to a supergroup. You can find to which supergroup the group was upgraded using field `basicGroup.upgraded_to_supergroup_id`. Then you can use the method `createSupergroupChat` to get corresponding `Сhat` and use the chat instead of the basic group afterwards.

> What is mean - "synchronized with the server"? How it works? What should I do?

It means that adding new user to the chat is a "synchronous" operation. For example, the user will not be returned in the `basicGroupFullInfo.members` list until the action will be completed server-side.

**Comment by jonua** [comment]
how to get status for a group? (is_active=false/true). When client receives an objects like `UpdateNewChat`, `UpdateBasicGroupFullInfo`, `UpdateSupergroupFullInfo` - flag `is_active` doesn't exists in thats objects

**Comment by levlam** [comment]
`Chat.type` contains `basic_gorup_id` for basic groups. Status `basicGroup.is_active` was received previously by the client in `updateBasicGroup`.

**Comment by jonua** [comment]
ok, thanks @levlam. Can I ask in this issue - Is there a document that describes the rules for setting identifiers for groups? In which case negative values are used, in which case is the prefix -100 and so on added to the group id etc.?

**Comment by levlam** [comment]
The rule is "never try to interpret ID's value and use provided by TDLib methods to handle it". Otherwise your code will be broken one day.

For example, use `Chat.type` to convert between `chat_id` and `user_id`/`basic_group_id`/`supergroup_id`/`secret_chat_id` and `create*Chat` for backward conversion.

**Comment by jonua** [comment]
I did not understand about backward conversion.
For example, I have a supergroup with *id==-100123* and *supergroupId==123*. If I understood correctly I should use the *supergroupId* (123) in the `TdApi.ChatMemberStatusLeft` method, rigth? But in this case I receive the error
> code = 3, message = "Chat not found"
How to call this method in correctly way?

**Comment by levlam** [comment]
You should not mix up `chat_id` and `supergroup_id`. Most methods requires `chat_id`, including `setChatMemberStatus`. So just pass `chat_id`, you usually need `supergroup_id` only to find some supergroup-specific information about the chat.
