### ISSUE TITLE
Is there a rate limit for downloadFile API ?

### ISSUE THREAD

**Issue by stanleyG123** [tdlib/td#820]
Is there a limit on how many times I can call downloadFile from one client before being put on the cooldown timer? 

I don't see anything of that nature in the documentation.

**Comment by levlam** [comment]
Every method has limits, explicit or implicit. But there is no such thing as a cooldown, which affects allowed number of requests. You can't exceed these limits but you can send as much requests as you want and only the same limited number of them will be executed. The limits are not documented anywhere, because they are subject to change, approximate and client don't need to know them at all. App just need to call `downloadFile` when it needs to download a file and the rest is done by TDLib.

**Comment by stanleyG123** [comment]
Currently, TdLib downloads a small image automatically.  To get a larger, I have to call downloadFile API explicitly.  Assuming I have to call the API on every image for every 200 channels I'm subscribed to, am I likely to hit the limit? 
thanks

**Comment by levlam** [comment]
TDLib doesn't download files automatically, see https://github.com/tdlib/td/issues/156.

You should call `downloadFile` whenever you need to download a file and never worry about possibility to hit a limit. Whether app will hit a limit or not doesn't depend much on how much `downloadFile` calls app do. If a limit is hit, it is usually automatically handled by TDLib and file continues to download when flood wait time passes.

**Comment by stanleyG123** [comment]
Perfect, thanks as always Aleksey !!
