### ISSUE TITLE
USER_NOT_MUTUAL_CONTACT: any ways to add "unknown" user to a chat?

### ISSUE THREAD

**Issue by jonua** [tdlib/td#821]
Hi,
If I trying to add user to supergroup using [TdApi.AddChatMember](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1add_chat_member.html) method, I receive an error

> code = 400, message = "USER_NOT_MUTUAL_CONTACT"

ok, I understand - spam protection etc.

But if I trying to add a user who is not in my contact list using official telegram client and my tg account - user adds to group without any troubles. What difference between official tg-client and tdLib client? I really, really can't add users who are not in my contact list to chats using tdLib?

**Comment by levlam** [comment]
USER_NOT_MUTUAL_CONTACT is returned for users left the group themselves. After that only mutual contact can invite them back. If the user is not a mutual contact, was previously a member of the group and left it, then the error USER_NOT_MUTUAL_CONTACT will be returned in any client.

**Comment by jonua** [comment]
where I can read a docs about statuses?

**Comment by levlam** [comment]
What statuses?

**Comment by jonua** [comment]
USER_NOT_MUTUAL_CONTACT, PEER_FLOOD etc

**Comment by levlam** [comment]
There is no description of all possible errors because they are subject to change often.

If an error is supposed to be handled in a special way by clients, you can find its description in source code of official clients. For example, you can find shown to user error messages in Android client in [AlertsCreator.java](https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/src/main/java/org/telegram/ui/Components/AlertsCreator.java).

**Comment by jonua** [comment]
ok, thanks @levlam
