### ISSUE TITLE
Download media

### ISSUE THREAD

**Issue by yasharzb** [tdlib/td#833]
Hi. After getting message which its content was a photo, I noticed that there are 3 sizes available. I saw type m, x and y. Is the y type the real quality of the photo?
Also there was s type for a video. Is there other video types available?

**Comment by RememberTheAir** [comment]
Photo objects (photo, userProfilePhoto etc.) have different sizes because you don't always need the highest resolution version of the photo (eg. needing to show a thumbnail or needing to show someone's small profile picture in a chat). Videos are not provided with different sizes - they are served as they were originally uploaded. Btw, similarly to photos, video objects usually come with a thumbnail property too which contains a list of photoSize that I suppose contains the thumbnail photo in different sizes

**Comment by yasharzb** [comment]
Aha. So for downloading the video I need to download this?
```
			"video": {
				"id": 14,
				"size": 46893039,
				"expectedSize": 46893039,
				"local": {
					"path": "",
					"canBeDownloaded": true,
					"canBeDeleted": false,
					"isDownloadingActive": false,
					"isDownloadingCompleted": false,
					"downloadOffset": 0,
					"downloadedPrefixSize": 0,
					"downloadedSize": 0
				},
				"remote": {
					"id": "BAADBAAD4QUAAuZtgVPYRkOWHPQinhYE",
					"isUploadingActive": false,
					"isUploadingCompleted": true,
					"uploadedSize": 46893039
				}
			}

```

**Comment by yasharzb** [comment]
And another question is about File Id.
For instance I created a channel and I sent first 2 photos and then a video. The video size was 44 MB. I noticed that the id's of second photo I sent changed. At first it was 6, 7, 8 and after uploading the video was 3 , 4, 5. And now the first photo has 10, 11, 12 id, second one has 3, 4, 5 id and the video has 13, 14. Where is the media with 1, 2, 6, 8, 9 ids?

**Comment by levlam** [comment]
@yasharzb Other IDs are assigned to some other files, for example, chat or user photos. Some assigned IDs may be even never returned to the app.

**Comment by yasharzb** [comment]
Do file ids change if I turn off the autoDownoad? I mean if I want to ensure that the file Id refers to the file I need can I use it after a while? Or it might has changed?

**Comment by levlam** [comment]
File.ids are not persistent and are valid only before TDLib instance is closed. TDLib has no autodownload concept, all files must be explicitly downloaded by the application.
