### ISSUE TITLE
instruction to draw bitmap from key_hash in secretChat are not clear

### ISSUE THREAD

**Issue by mymike00** [tdlib/td#874]
in [secretChat](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1secret_chat.html#aba56ad755c83229a81a6a9f4c8782b30) docs there's described the method to draw a 20x20 matrix from the key_hash field. I tried to follow those instructions but I failed to draw the same image as shown on the other user's client, while the raw hexadecimal string matches (that had to me decoded from base64 tbh, which isn't mentioned on the doc). [here](https://gitlab.com/ubports/apps/teleports/merge_requests/267/diffs#ecb9dfb9cb95c20ec9ba54b76885c6d3670ef214_70_82) is my attempt, if that could help... I'd be happy also if you can point me to the code in one of the other clients

**Comment by levlam** [comment]
Type of `key_hash` is `bytes`, which is additionally base64-encoded in JSON interface to be a valid UTF-8 string. That's why you need to base64-decode it if you use the JSON interface.

You can find example implementation in the official Telegram Android app source: https://github.com/DrKLO/Telegram/blob/31736964fa12b5981632ecfd75d5f6d4f91f7135/TMessagesProj/src/main/java/org/telegram/ui/Components/IdenticonDrawable.java#L71.

In TDLib `key_hash` length is always 36, so case `data.length == 16` is not needed at all.

From the code it seems that the 12x12 square is just filled left to right, top to bottom.

**Comment by mymike00** [comment]
Thanks for your instant reply!
The only thing I don't understand is why the first pixel of the matrix is drawn using the last (LSB) 2 bits of the first byte and the first (MSB) 2 bits of that first byte are used to draw the 4th pixel. Why this order?

**Comment by levlam** [comment]
@mymike00 This is a regular little-endian order.

**Comment by mymike00** [comment]
> @mymike00 This is a regular little-endian order.

oh ok, my fault for that then. I'm not used to deal with such low level data. I haven't managed yet to draw properly the matrix on our client but you helped me a lot. Thank you!

**Comment by mymike00** [comment]
another weird thing I found is that the value of the 2 bits used to draw a pixel in the matrix doesn't correspond to the darkness of the color: 0 is white, 1 is a bit darker, 2 is the darkest color and 3 is less dark that 2...

**Comment by levlam** [comment]
@mymike00 Yes, you need to use colors https://github.com/DrKLO/Telegram/blob/31736964fa12b5981632ecfd75d5f6d4f91f7135/TMessagesProj/src/main/java/org/telegram/ui/Components/IdenticonDrawable.java#L23.

**Comment by mymike00** [comment]
sure I used them, I was just wondering why that choice...
