### ISSUE TITLE
PII leakage when mentioning someone without username

### ISSUE THREAD

**Issue by Dreista** [tdlib/td#883]
### Steps to reproduce
1. Suppose that we have a user A without username;
2. Add user A to contact, set his first name to "blahblahblah";
3. Mention this user in a group.

### Expected behavior
Only the last name / first name **set by user A** is displayed.

### Actual behavior
An underlined "blahblahblah" (first name) is displayed. On Telegram Android, user A's last name is also displayed.

### Configuration
Affected clients include Telegram Android, Telegram iOS/macOS, Unigram, and Telegram Desktop. Not yet tested on Telegram X on Android.

**Comment by Hexhu** [comment]
I have long hoped that when I @mention my friends in a PUBLIC group chat, I won't _accidentally_ leak the "custom nickname" I set for them. Currently the nicknames will be sent **by default**, and editing the @mention URL is not easy.

It would be more appropriate if I am allowed to only send their PUBLIC name by default.

It is okay when the nicknames are set _intentionally_ and sent _intentionally_, but it becomes problematic when Telegram imports the "custom nicknames" with the names from my phone's contact manager... And they are mostly REAL NAMES and I want to keep them absolutely **private** in a PUBLIC group.

Apparently the isolation between my phone's contact manager and the Telegram's is pretty broken, and lots of Personal Identifiable Information are at risk of accidental leakage.

Please fix this! :3

**Comment by Hexhu** [comment]
Did a very brief search in the codebase:

The "custom nickname" might be set by `ContactsManager::update_user()`

When typing the @mention, tdlib might be using a `td_api::textEntityTypeMentionName` or a `entity_mention_name`, where the "custom nickname" enters the text entry by default.

The "custom nickname" will likely to carry Personal Identifiable Information and should NOT be typed into the text entry by default.

It would be better if in `MessageEntity.cpp`(?), the `entity_mention_name->user_id_` is the PUBLIC NAME of the mentioned user, rather than our personal "custom nickname" as it appears in the Telegram `ContactsManager`.

Hope this helps.

**Comment by levlam** [comment]
This nothing to do with TDLib, the text behind the mention is provided by app using TDLib. Moreover, the text can be anything you want, because all apps allow to edit it before the message is sent. The name leakage situation is the same as you accidentally write real person name by hands in the chat, because this is what you actually see everywhere.
