### ISSUE TITLE
clear_draft field in inputMessageText usage isn't clear

### ISSUE THREAD

**Issue by mymike00** [tdlib/td#901]
So, from what I got from debugging, I never receive an `inputMessageText` with `"clear_draft": true` since when I receive an `updateChatDraftMessage` the whole `draft_message` object is missing if the draft is empty.
I saw that when sending a message in a chat where there's a draft saved `clear_draft` needs to be true otherwise the draft is still there after the message is sent. Is this one the only usage of this field or not? Other then when I send a message, it should always be false, right?
Thanks

**Comment by levlam** [comment]
The field `clear_draft` needs to be used only when a text message is sent in order to simultaneously clear the draft in the chat. The field is meaningless inside the `draftMessage` object, because until the message is sent the field doesn't affect anything. If the message is sent in an ordinary way, `draft_message` should be set to true. If message is sent not from the ordinary input field, then the field should be set to false.

**Comment by mymike00** [comment]
Okay, perfect. A more detailed description in the docs could help btw!
