### ISSUE TITLE
Git tags for minor versions

### ISSUE THREAD

**Issue by ForNeVeR** [tdlib/td#913]
Could you please start adding git tags for minor versions, such as 1.5.1 or 1.5.4? This is important for maintainers of downstream builds.

**Comment by levlam** [comment]
These versions are not supposed to be used as release versions and are not supposed to be used at all after next minor version release, for example, 1.6.0. They aren't well tested and can have a lot of known and unknown issues. Because of that they are not recommended for general usage.

**Comment by ForNeVeR** [comment]
But they should be used _before_ the minor release, right? So there's a valid time span when these versions should be used?

**Comment by levlam** [comment]
Not exactly. They can be used for testing purposes and early implementation of new features, but they are not recommended to be used for production releases, because it is usually unknown whether they are suitable for production. So, if you prefer stability, you can use the last release version. If you prefer bleeding edge features, then it is better to use the last development version from master. Whatever commit is tagged with patch version, it would be just a random outdated commit.

**Comment by ForNeVeR** [comment]
Aha, so these patch releases should be considered as preview before a new minor 1.x coming out, right?

**Comment by levlam** [comment]
Yes. Before 1.5.0 the source code wasn't even pushed to Github before the actual release.

**Comment by levlam** [comment]
Tagged TDLib 1.7.0 version has been released.
