### ISSUE TITLE
Notification triggered from same contact or chat group

### ISSUE THREAD

**Issue by 24mu13** [tdlib/td#930]
I have some (annoying) friend sending several messages in sequence, like the following:
```
hey
how are you?
still sick?
```

In this case I will receive THREE notifications (sound), disturbing and useless. Not to mention the same scenario in a chat-group, where everybody is texting at the same time! Nightmare.

Is it possible to add a field like **is_again_** on [notification](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1notification.html) event in order to mitigate/configure another UX? This flag should indicate same user or group within a sort of short time-slice, like 30secs.

Since I use [Depecher](https://github.com/blacksailer/depecher) on my phone, I am not sure this is already handled on official app...

**Comment by levlam** [comment]
There is no need in additional fields, this could be done via `updateNotificationGroup.is_silent` flag. But the correct behavior is not evident there. Some people want to be notified on all incoming messages. For now, the rate limiting of notifications with sound is supposed to be done by the client, because sound needs to be skipped even for notifications from different chats arriving at the same time.

**Comment by levlam** [comment]
This will be added on TDLib's side if such setting appears in one of the official clients. For now this feature can be implemented client-side with minimal effort.
