### ISSUE TITLE
Exception Handler doesn't catch

### ISSUE THREAD

**Issue by yasharzb** [tdlib/td#943]
Hi. I used a custom exceptionHandler like this:
```
public class CustomExceptionHandler implements Client.ExceptionHandler {
    @Override
    public void onException(Throwable throwable) {
       //......
    }
}
```
and somewhere else I used         
`client.send(new TdApi.GetMessage(chatId, messageId), new CustomResultHandler(), new CustomExceptionHandler();`
the `onResult` method of `CustomResultHandler` is:
```
public void onResult(TdApi.Object object) {
     if (object.getConstructor() == TdApi.Message.CONSTRUCTOR) {
         //.......
     } else {
         throw new DeletedMessageException();
     }
 }

```
When I throw an exception in `onResult` method of `CustomResultHandler`, I can process it in `CustomExceptionHandler` but then it throws it again to outer layer. And when I catch it in outer layer the `CustomExceptionHandler` never receives the exception. What should I do?

**Comment by levlam** [comment]
All result handlers are invoked asynchronously on a dedicated thread. A custom exception handler can be used to catch an exception thrown by the result handler, but there is noone who can handle an exception thrown from the exception handler, because this happens on another thread. So the exception is always silently ignored. You can find all this implemented there: https://github.com/tdlib/td/blob/c407b244a086e71773e0b9f8f64d4fb0536bc447/example/java/org/drinkless/tdlib/Client.java#L253.
