### ISSUE TITLE
FR: searchMessagesFilterThread

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#960]
There is nice idea seen in https://t.me/designers/44

However this feature is hard to implement correctly only on client side, because if some old random message is chosen as thread initiation, it will require fetching full chat history to get all the replies to this message.

It will be nice to have messages filter such as:
```
searchMessagesFilterThread message_id:int53 = SearchMessagesFilter;
```
to search all the messages related to the `message_id`.  By "related" I mean all the messages eventually leading to the `message_id` by forward or backward recursive traversion of the `reply_to_message_id` message property.

What do you think? Thanks

**Comment by levlam** [comment]
"Forward recursive traversion" is easy to implement successively calling `getRepliedMessage`.
"Backward recursive traversion" can't be implemented without the server-side index. There is no such index now and it is very-very unlikely to be added in the future due to performance and usability reasons. If the index is added, then after any reply to a message information about the replied message needs to be updated, adding new reply to the list. Moreover, if recursive replies are needed, then unlimited number of messages may need to be updated.
From the other side there is no guarantee that the feature will be usable, because some actually "thread" messages may not have `reply_to_message_id` field and some important information will be missed.

**Comment by levlam** [comment]
The feature was added, but limited to supergroups linked to channels and threads beginning from a message, which is not a reply.

The problem with "reply_to_message_id" was solved by automatic adding of it when a message is sent from thread view interface.
