### ISSUE TITLE
Location updates for messageLocation

### ISSUE THREAD

**Issue by zevlg** [tdlib/td#964]
In TDLib 1.5.0 (and earlier versions I think) there was a nice feature - before sending `updateMessageContent` event for live location message, TDLib used to send `updateMessageEdited` event.  So, client easily can display something like "updated 7 minutes ago" just by subtracting current time and "edit_date" of the message.

With TDLib 1.6.0 this is no longer a case, `updateMessageEdited` is not reported before location update with `updateMessageContent` event.  So, to display  "updated 7 minutes ago", client needs to store somewhere timestamp of the `updateMessageContent` event in case it carries location content 

Is it intended behaviour change?  Why disabling `updateMessageEdited` events for live location updates?

Thanks

**Comment by levlam** [comment]
Since version 1.5.3 TDLib uses server-provided flag to automatically hide `edit_date` field for messages, which should not be shown as edited to the user. It has happenned that the server marks all live location messages with the flag, because there should be no `edited` mark on them. But nevertheless `edit_date` is needed to be shown to the user for live locations, so this will be fixed on TDLib's side.

**Comment by levlam** [comment]
This was fixed in TDLib 1.6.2 a few days after the issue was created.
