### ISSUE TITLE
There is a message on the channel but GetMessages method return null

### ISSUE THREAD

**Issue by BehzadArabi** [tdlib/td#997]
Hi. I use the GetMessages method to get the information of a message. The problem I have is that there is a message in the channel, but sometimes the GetMessages method returns the null value. And if I try again, it gives me the message information. What is the cause of this problem? (I use proxy)

**Comment by levlam** [comment]
It seems that you are calling `GetMessages` with a `message_id` received not from the TDLib instance. TDLib can't return a message, which is after last known message in the chat, because it will mess up the chat message history. It will be returned only after the chat history is synchronized up to the message.

**Comment by BehzadArabi** [comment]
You are right.
I want to get information of a message which is received from telegram link.
So what is the best way?

**Comment by levlam** [comment]
See all the answers in https://github.com/tdlib/td/issues/644.

**Comment by BehzadArabi** [comment]
Thanks!
